<?php
$pageTitle='Fournisseur';$activePage='stocks';require __DIR__.'/includes/bootstrap.php';require __DIR__.'/includes/ux_objects.php';requerirConnexion();runSchemaMigrations();$db=getDB();$pid=(int)($_GET['projet_id']??0);$projet=$pid?pfLoadProject($pid):null;$fid=(int)($_GET['id']??0);$aid=(int)($_GET['article_id']??0);
if(!$fid&&$aid){$q=$db->prepare('SELECT fournisseur_id FROM stock_article_fournisseur WHERE article_id=? ORDER BY preferentiel DESC,id LIMIT 1');$q->execute([$aid]);$fid=(int)$q->fetchColumn();}
$q=$db->prepare('SELECT * FROM stock_fournisseurs WHERE id=?');$q->execute([$fid]);$supplier=$q->fetch();if(!$supplier){setFlash('error','Aucun fournisseur lié à cet article.');redirect('stock_fournisseurs.php');}
$q=$db->prepare('SELECT a.*,af.reference_fournisseur,af.prix,af.delai_jours FROM stock_articles a JOIN stock_article_fournisseur af ON af.article_id=a.id WHERE af.fournisseur_id=?');$q->execute([$fid]);$articles=$q->fetchAll();
$q=$db->prepare('SELECT DISTINCT p.id,p.nom FROM projets p JOIN stock_usages su ON su.projet_id=p.id JOIN stock_article_fournisseur af ON af.article_id=su.article_id WHERE af.fournisseur_id=?');$q->execute([$fid]);$projects=array_values(array_filter($q->fetchAll(),fn($p)=>projectCanContribute($db,(int)$p['id'],utilisateurCourant())));require __DIR__.'/includes/header.php';?>
<div class="page-header"><div><span class="pf-tag">FOURNISSEUR</span><h1><?=e($supplier['nom'])?></h1><p><?=e($supplier['contact']?:'Contact non renseigné')?></p></div><a class="btn btn-secondary" href="<?=url('stock_fournisseurs.php?edit='.$fid)?>">Modifier la fiche</a></div>
<div class="pf-grid"><section class="card card-body"><h2>Contact & informations</h2><p><?=e($supplier['email']?:'E-mail non renseigné')?> · <?=e($supplier['telephone']?:'Téléphone non renseigné')?></p><p class="pf-technical-summary"><?=e($supplier['notes']??'')?></p></section><section class="card card-body"><h2>Qualité documentaire</h2><?php foreach(['9001','14001'] as $iso):?><p>ISO <?=$iso?> · <span class="pf-tag"><?=e($supplier['iso'.$iso.'_statut']??'Non renseigné')?></span> <?=e($supplier['iso'.$iso.'_numero']??'')?> · <?=e($supplier['iso'.$iso.'_validite']??'')?></p><?php endforeach;?><p class="text-muted">Les déclarations et preuves sont consultables dans la qualité du projet concerné.</p></section></div>
<div class="card card-body" style="margin-top:20px"><h2>Articles associés</h2><table class="table"><thead><tr><th>Référence</th><th>Désignation</th><th>Référence fournisseur</th><th>Disponibilité</th><th>Délai catalogue</th></tr></thead><tbody><?php foreach($articles as $a):?><tr><td><a href="<?=url('stock_article.php?id='.(int)$a['id'])?>"><?=e($a['reference'])?></a></td><td><?=e($a['designation'])?></td><td><?=e($a['reference_fournisseur']??'—')?></td><td><?=e((string)$a['quantite_stock'])?> <?=e($a['unite'])?></td><td><?=e((string)($a['delai_jours']??'Non renseigné'))?></td></tr><?php endforeach;?></tbody></table></div>
<section class="card card-body" style="margin-top:20px"><h2>Projets utilisateurs & preuves</h2><?php foreach($projects as $p):?><div class="dash-task-row"><a href="<?=url('projet.php?id='.(int)$p['id'])?>"><?=e($p['nom'])?></a><div class="pf-links"><a href="<?=url('qualite_projet.php?projet_id='.(int)$p['id'])?>">ISO / RoHS / REACH</a><a href="<?=url('projet.php?id='.(int)$p['id'].'&view=processus&step=5')?>">Achats</a><a href="<?=url('documents_externes.php?projet_id='.(int)$p['id'])?>">Documents</a></div></div><?php endforeach;?><?php if(!$projects):?><p class="pf-empty">Aucun projet utilisateur visible via les relations de stock.</p><?php endif;?></section>
<?php require __DIR__.'/includes/footer.php';?>
