<?php
$pageTitle='Système de management'; $activePage='management';
require_once __DIR__.'/includes/bootstrap.php'; requerirConnexion(); runSchemaMigrations();
$db=getDB();
$tabs=['processus'=>'Processus','documents'=>'Documents maîtrisés','risques'=>'Risques & opportunités','actions'=>'Actions','nc'=>'Non-conformités','enregistrements'=>'Enregistrements'];
$tab=$_GET['tab']??'processus'; if(!isset($tabs[$tab]))$tab='processus';
if($_SERVER['REQUEST_METHOD']==='POST'){ csrfRequire(); $a=$_POST['action']??'';
 try{
  requerirAdmin();
  if($a==='processus'){$db->prepare("INSERT INTO processus(code,nom,pilote,description) VALUES(?,?,?,?)")->execute([trim($_POST['code']),trim($_POST['nom']),trim($_POST['pilote']),trim($_POST['description'])]);}
  elseif($a==='document'){if(!in_array($_POST['statut']??'', ['brouillon','en_revue'],true))throw new InvalidArgumentException('Créer un brouillon puis approuver dans le suivi avec preuve.');$db->prepare("INSERT INTO documents_controles(reference,titre,type,processus_id,projet_id,statut,version,auteur,date_creation,description) VALUES(?,?,?,?,?,?,?,?,?,?)")->execute([trim($_POST['reference']),trim($_POST['titre']),trim($_POST['type']),($_POST['processus_id']?:null),($_POST['projet_id']?:null),trim($_POST['statut']),trim($_POST['version']),trim($_POST['auteur']),date('Y-m-d'),trim($_POST['description'])]);}
  elseif($a==='risque'){$p=(int)$_POST['probabilite'];$i=(int)$_POST['impact'];if($p<1||$p>5||$i<1||$i>5)throw new InvalidArgumentException('Probabilité et impact : valeurs de1 à5.');$db->prepare("INSERT INTO risques_opportunites(processus_id,projet_id,type,description,cause,consequence,probabilite,impact,criticite,action_prevue,responsable,echeance) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)")->execute([($_POST['processus_id']?:null),($_POST['projet_id']?:null),$_POST['type'],trim($_POST['description']),trim($_POST['cause']),trim($_POST['consequence']),$p,$i,$p*$i,trim($_POST['action_prevue']),trim($_POST['responsable']),($_POST['echeance']?:null)]);}
  elseif($a==='actionq'){$db->prepare("INSERT INTO actions_qualite(processus_id,projet_id,type,origine,description,responsable,echeance) VALUES(?,?,?,?,?,?,?)")->execute([($_POST['processus_id']?:null),($_POST['projet_id']?:null),trim($_POST['type']),trim($_POST['origine']),trim($_POST['description']),trim($_POST['responsable']),($_POST['echeance']?:null)]);}
  elseif($a==='nc'){$ref='NC-'.date('Ymd-His');$db->prepare("INSERT INTO non_conformites(reference,processus_id,projet_id,description,detection,disposition,responsable,echeance) VALUES(?,?,?,?,?,?,?,?)")->execute([$ref,($_POST['processus_id']?:null),($_POST['projet_id']?:null),trim($_POST['description']),trim($_POST['detection']),trim($_POST['disposition']),trim($_POST['responsable']),($_POST['echeance']?:null)]);}
  elseif($a==='record'){
   $date=(string)($_POST['date_metier']??'');$parsed=DateTimeImmutable::createFromFormat('!Y-m-d',$date);
   if(!$parsed||$parsed->format('Y-m-d')!==$date)throw new InvalidArgumentException('Date métier invalide.');
   $proof=(int)($_POST['document_id']??0)?:null;$project=(int)($_POST['projet_id']??0)?:null;
   if($proof){$q=$db->prepare('SELECT projet_id FROM documents_controles WHERE id=?');$q->execute([$proof]);$d=$q->fetch();if(!$d||!$project||(int)$d['projet_id']!==$project)throw new InvalidArgumentException('Le document maîtrisé doit appartenir au projet de l’enregistrement.');}
   $notes=trim($_POST['notes'])."\nEnregistré par acteur #".(int)utilisateurCourant()['id'].' le '.date('Y-m-d H:i:s').'.';
   $db->prepare("INSERT INTO enregistrements(type,reference,processus_id,projet_id,document_id,date_evenement,resultat,statut,notes) VALUES(?,?,?,?,?,?,?,?,?)")->execute([trim($_POST['type']),trim($_POST['reference']),($_POST['processus_id']?:null),$project,$proof,$date.' 00:00:00',trim($_POST['resultat']),trim($_POST['statut']),$notes]);
  }
  setFlash('success','Enregistrement créé.'); redirect('management.php?tab='.$tab);
 }catch(Throwable $e){setFlash('error','Erreur : '.$e->getMessage());}
}
$processus=$db->query("SELECT * FROM processus ORDER BY code")->fetchAll();
$projets=$db->query("SELECT id,nom FROM projets ORDER BY nom")->fetchAll();
$controlled=$db->query("SELECT id,reference FROM documents_controles ORDER BY reference")->fetchAll();
$counts=[
 'processus'=>(int)$db->query("SELECT COUNT(*) FROM processus WHERE actif=1")->fetchColumn(),
 'documents'=>(int)$db->query("SELECT COUNT(*) FROM documents_controles")->fetchColumn(),
 'risques'=>(int)$db->query("SELECT COUNT(*) FROM risques_opportunites WHERE statut NOT IN ('clos','ferme')")->fetchColumn(),
 'actions'=>(int)$db->query("SELECT COUNT(*) FROM actions_qualite WHERE statut NOT IN ('close','cloturee')")->fetchColumn(),
 'nc'=>(int)$db->query("SELECT COUNT(*) FROM non_conformites WHERE statut!='cloturee'")->fetchColumn()
];
require __DIR__.'/includes/header.php';
function opts($rows,$key,$label){foreach($rows as $r)echo '<option value="'.(int)$r[$key].'">'.e($r[$label]).'</option>';}
?>
<div class="page-header"><div><h1><i class="fas fa-sitemap"></i> Système de management</h1><p class="text-muted">Pilotage générique qualité, environnement et traçabilité.</p></div></div>
<div class="dash-kpi-grid">
<?php foreach(['processus'=>'Processus actifs','documents'=>'Documents','risques'=>'Risques ouverts','actions'=>'Actions ouvertes','nc'=>'NC ouvertes'] as $k=>$l): ?><div class="dash-kpi"><p class="dash-kpi-label"><?=e($l)?></p><p class="dash-kpi-value"><?=$counts[$k]?></p></div><?php endforeach;?>
</div>
<div class="card" style="padding:.75rem;margin:1rem 0;display:flex;gap:.5rem;flex-wrap:wrap">
<?php foreach($tabs as $k=>$l):?><a class="btn <?=$tab===$k?'btn-primary':'btn-secondary'?> btn-sm" href="<?=url('management.php?tab='.$k)?>"><?=e($l)?></a><?php endforeach;?>
</div>
<?php if($tab==='processus'): $rows=$db->query("SELECT * FROM processus ORDER BY code")->fetchAll(); ?>
<div class="card" style="padding:1rem"><h2>Cartographie des processus</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="processus"><div class="form-row"><input class="form-control" name="code" placeholder="Code" required><input class="form-control" name="nom" placeholder="Nom du processus" required><input class="form-control" name="pilote" placeholder="Pilote"></div><textarea class="form-control" name="description" placeholder="Finalité, entrées, sorties, indicateurs..."></textarea><button class="btn btn-primary btn-sm">Ajouter</button></form>
<table class="table"><thead><tr><th>Code</th><th>Processus</th><th>Pilote</th><th>Description</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['code'])?></td><td><?=e($r['nom'])?></td><td><?=e($r['pilote'])?></td><td><?=e($r['description'])?></td></tr><?php endforeach;?></tbody></table></div>
<?php elseif($tab==='documents'): $rows=$db->query("SELECT d.*,p.nom processus FROM documents_controles d LEFT JOIN processus p ON p.id=d.processus_id ORDER BY d.id DESC")->fetchAll(); ?>
<div class="card" style="padding:1rem"><h2>Documents maîtrisés</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="document"><div class="form-row"><input class="form-control" name="reference" placeholder="Référence" required><input class="form-control" name="titre" placeholder="Titre" required><input class="form-control" name="type" value="procedure" placeholder="Type"><select class="form-control" name="processus_id"><option value="">Processus</option><?php opts($processus,'id','nom');?></select><select class="form-control" name="projet_id"><option value="">Projet</option><?php opts($projets,'id','nom');?></select><input class="form-control" name="version" value="1.0"><select class="form-control" name="statut"><option>brouillon</option><option>en_revue</option></select><input class="form-control" name="auteur" placeholder="Auteur"></div><textarea class="form-control" name="description" placeholder="Objet / périmètre"></textarea><button class="btn btn-primary btn-sm">Créer le document</button></form>
<table class="table"><thead><tr><th>Réf.</th><th>Titre</th><th>Type</th><th>Version</th><th>Statut</th><th>Processus</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['reference'])?></td><td><?=e($r['titre'])?></td><td><?=e($r['type'])?></td><td><?=e($r['version'])?></td><td><?=e($r['statut'])?> <a href="<?=url('management_fiche.php?type=document&id='.(int)$r['id'])?>">Suivre #<?=(int)$r['id']?></a></td><td><?=e($r['processus']??'—')?></td></tr><?php endforeach;?></tbody></table></div>
<?php elseif($tab==='risques'): $rows=$db->query("SELECT r.*,p.nom processus,pr.nom projet FROM risques_opportunites r LEFT JOIN processus p ON p.id=r.processus_id LEFT JOIN projets pr ON pr.id=r.projet_id ORDER BY criticite DESC,id DESC")->fetchAll(); ?>
<div class="card" style="padding:1rem"><h2>Risques & opportunités</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="risque"><div class="form-row"><select class="form-control" name="type"><option value="risque">Risque</option><option value="opportunite">Opportunité</option></select><select class="form-control" name="processus_id"><option value="">Processus</option><?php opts($processus,'id','nom');?></select><select class="form-control" name="projet_id"><option value="">Projet</option><?php opts($projets,'id','nom');?></select><input class="form-control" type="number" min="1" max="5" name="probabilite" value="1" title="Probabilité"><input class="form-control" type="number" min="1" max="5" name="impact" value="1" title="Impact"></div><textarea class="form-control" name="description" required placeholder="Description"></textarea><div class="form-row"><input class="form-control" name="cause" placeholder="Cause"><input class="form-control" name="consequence" placeholder="Conséquence"><input class="form-control" name="action_prevue" placeholder="Action prévue"><input class="form-control" name="responsable" placeholder="Responsable"><input class="form-control" type="date" name="echeance"></div><button class="btn btn-primary btn-sm">Enregistrer</button></form>
<table class="table"><thead><tr><th>Type</th><th>Description</th><th>P×I</th><th>Processus / Projet</th><th>Action</th><th>Resp.</th><th>Statut</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['type'])?></td><td><?=e($r['description'])?></td><td><strong><?=e((string)$r['criticite'])?></strong></td><td><?=e(($r['processus']??'').' '.($r['projet']??''))?></td><td><?=e($r['action_prevue'])?></td><td><?=e($r['responsable'])?></td><td><?=e($r['statut'])?> <a href="<?=url('management_fiche.php?type=risque&id='.(int)$r['id'])?>">Suivre #<?=(int)$r['id']?></a></td></tr><?php endforeach;?></tbody></table></div>
<?php elseif($tab==='actions'): $rows=$db->query("SELECT a.*,p.nom processus,pr.nom projet FROM actions_qualite a LEFT JOIN processus p ON p.id=a.processus_id LEFT JOIN projets pr ON pr.id=a.projet_id ORDER BY a.id DESC")->fetchAll(); ?>
<div class="card" style="padding:1rem"><h2>Plan d'actions</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="actionq"><div class="form-row"><input class="form-control" name="type" value="amelioration" placeholder="Type"><input class="form-control" name="origine" placeholder="Origine"><select class="form-control" name="processus_id"><option value="">Processus</option><?php opts($processus,'id','nom');?></select><select class="form-control" name="projet_id"><option value="">Projet</option><?php opts($projets,'id','nom');?></select><input class="form-control" name="responsable" placeholder="Responsable"><input class="form-control" type="date" name="echeance"></div><textarea class="form-control" name="description" required placeholder="Action à réaliser"></textarea><button class="btn btn-primary btn-sm">Ajouter</button></form>
<table class="table"><thead><tr><th>Type</th><th>Origine</th><th>Action</th><th>Responsable</th><th>Échéance</th><th>Statut</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['type'])?></td><td><?=e($r['origine'])?></td><td><?=e($r['description'])?></td><td><?=e($r['responsable'])?></td><td><?=e($r['echeance'])?></td><td><?=e($r['statut'])?> <a href="<?=url('management_fiche.php?type=action&id='.(int)$r['id'])?>">Suivre #<?=(int)$r['id']?></a></td></tr><?php endforeach;?></tbody></table></div>
<?php elseif($tab==='nc'): $rows=$db->query("SELECT n.*,p.nom processus,pr.nom projet FROM non_conformites n LEFT JOIN processus p ON p.id=n.processus_id LEFT JOIN projets pr ON pr.id=n.projet_id ORDER BY n.id DESC")->fetchAll(); ?>
<div class="card" style="padding:1rem"><h2>Non-conformités</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="nc"><div class="form-row"><select class="form-control" name="processus_id"><option value="">Processus</option><?php opts($processus,'id','nom');?></select><select class="form-control" name="projet_id"><option value="">Projet</option><?php opts($projets,'id','nom');?></select><input class="form-control" name="detection" placeholder="Détection / origine"><input class="form-control" name="responsable" placeholder="Responsable"><input class="form-control" type="date" name="echeance"></div><textarea class="form-control" name="description" required placeholder="Non-conformité constatée"></textarea><textarea class="form-control" name="disposition" placeholder="Disposition immédiate / confinement"></textarea><button class="btn btn-primary btn-sm">Ouvrir la NC</button></form>
<table class="table"><thead><tr><th>Réf.</th><th>Description</th><th>Détection</th><th>Disposition</th><th>Resp.</th><th>Statut</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['reference'])?></td><td><?=e($r['description'])?></td><td><?=e($r['detection'])?></td><td><?=e($r['disposition'])?></td><td><?=e($r['responsable'])?></td><td><?=e($r['statut'])?> <a href="<?=url('management_fiche.php?type=nc&id='.(int)$r['id'])?>">Suivre #<?=(int)$r['id']?></a></td></tr><?php endforeach;?></tbody></table></div>
<?php else: $rows=$db->query("SELECT e.*,p.nom processus,pr.nom projet,d.reference document_reference FROM enregistrements e LEFT JOIN documents_controles d ON d.id=e.document_id LEFT JOIN processus p ON p.id=e.processus_id LEFT JOIN projets pr ON pr.id=e.projet_id ORDER BY e.id DESC")->fetchAll(); ?>
<div class="card" style="padding:1rem"><h2>Enregistrements & preuves</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="record"><div class="form-row"><input class="form-control" name="type" placeholder="Type (contrôle, essai...)" required><input class="form-control" name="reference" placeholder="Référence"><select class="form-control" name="processus_id"><option value="">Processus</option><?php opts($processus,'id','nom');?></select><select class="form-control" name="projet_id"><option value="">Projet</option><?php opts($projets,'id','nom');?></select><label>Date métier<input class="form-control" type="date" name="date_metier" required value="<?=date('Y-m-d')?>"></label><select class="form-control" name="document_id"><option value="">Document maîtrisé</option><?php opts($controlled,'id','reference');?></select><input class="form-control" name="statut" value="valide" placeholder="Statut"></div><textarea class="form-control" name="resultat" placeholder="Résultat"></textarea><textarea class="form-control" name="notes" placeholder="Notes / preuve"></textarea><button class="btn btn-primary btn-sm">Enregistrer</button></form>
<table class="table"><thead><tr><th>Date métier</th><th>Type</th><th>Réf.</th><th>Résultat</th><th>Statut</th><th>Contexte</th><th>Preuve / notes</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['date_evenement'])?></td><td><?=e($r['type'])?></td><td><?=e($r['reference'])?></td><td><?=e($r['resultat'])?></td><td><?=e($r['statut'])?></td><td><?=e(($r['processus']??'').' '.($r['projet']??''))?></td><td><?php if($r['document_id']):?><a href="<?=url('management_fiche.php?type=document&id='.(int)$r['document_id'])?>"><?=e($r['document_reference'])?></a><?php endif;?><p style="white-space:pre-wrap"><?=e($r['notes'])?></p></td></tr><?php endforeach;?></tbody></table></div>
<?php endif; require __DIR__.'/includes/footer.php';?>