<?php
$pageTitle='Responsable';$activePage='taches';require __DIR__.'/includes/bootstrap.php';require __DIR__.'/includes/ux_objects.php';requerirConnexion();$pid=(int)($_GET['projet_id']??0);$projet=$pid?pfLoadProject($pid):null;$ident=trim((string)($_GET['identifiant']??''));
$q=getDB()->prepare('SELECT id,identifiant,nom_affiche,fonction,competences FROM utilisateurs WHERE identifiant=?');$q->execute([$ident]);$person=$q->fetch();if(!$person){setFlash('error','Utilisateur introuvable.');redirect('taches.php');}
$q=getDB()->prepare('SELECT t.*,p.nom projet_nom,p.createur_id FROM taches t JOIN projets p ON p.id=t.projet_id WHERE t.assigne_a=?'.($pid?' AND t.projet_id=?':'').' ORDER BY t.id');$q->execute($pid?[$ident,$pid]:[$ident]);$tasks=$q->fetchAll();$actor=utilisateurCourant();$tasks=array_values(array_filter($tasks,fn($t)=>estAdmin()||(int)$t['createur_id']===(int)$actor['id']||$t['assigne_a']===$actor['identifiant']));
if(!estAdmin()&&$ident!==$actor['identifiant']&&!$pid){setFlash('error','Sélectionnez un projet auquel vous contribuez.');redirect('taches.php');}
require __DIR__.'/includes/header.php';?>
<div class="page-header"><div><span class="pf-tag">RESPONSABLE</span><h1><?=e($person['nom_affiche']?:$ident)?></h1><p><?=e($ident)?> · <?=e($person['fonction']?:'Fonction non renseignée')?></p></div><?php if(estAdmin()):?><a class="btn btn-secondary" href="<?=url('admin/utilisateurs.php?action=modifier&id='.(int)$person['id'])?>">Gérer le profil</a><?php endif;?></div>
<div class="pf-grid"><section class="card card-body"><h2>Compétences déclarées</h2><p class="pf-technical-summary"><?=e($person['competences']?:'Non renseignées')?></p></section><section class="card card-body"><h2>Affectations visibles</h2><p><?=count($tasks)?> tâche(s). Les compétences déclarées ne constituent pas une mesure de disponibilité.</p></section></div>
<div class="card card-body" style="margin-top:20px"><h2>Tâches associées</h2><?php foreach($tasks as $t):?><div class="dash-task-row"><a href="<?=url('tache.php?id='.(int)$t['id'])?>">#<?=(int)$t['id']?> · <?=e($t['titre'])?></a><span class="pf-tag"><?=e(statutLabel($t['statut']))?></span></div><?php endforeach;?><?php if(!$tasks):?><p class="pf-empty">Aucune affectation visible.</p><?php endif;?></div>
<?php require __DIR__.'/includes/footer.php';?>
