<?php
$pageTitle='Planning & Gantt';$activePage='projets';require __DIR__.'/includes/bootstrap.php';require __DIR__.'/includes/ux_objects.php';require __DIR__.'/includes/decision_gantt.php';requerirConnexion();
$pid=(int)($_GET['projet_id']??0);$projet=pfLoadProject($pid);$specs=pfSpecs($pid);$q=getDB()->prepare('SELECT * FROM taches WHERE projet_id=? ORDER BY id');$q->execute([$pid]);$tachesAll=$q->fetchAll();if(!estAdmin()&&!projectCanManage(getDB(),$pid,utilisateurCourant()))$tachesAll=array_values(array_filter($tachesAll,fn($t)=>($t['assigne_a']??'')===utilisateurCourant()['identifiant']));
$sourceLink=fn($type)=>url('projet.php?id='.$pid.'&view=taches');require __DIR__.'/includes/header.php';?>
<link rel="stylesheet" href="<?=url('assets/css/decision-dashboard.css?v=night-1')?>">
<div class="page-header"><div><h1>Planning & Gantt</h1><p class="text-muted">Les dates prévues, les responsables et les dépendances des mêmes tâches.</p></div><a class="btn btn-primary" href="<?=url('projet.php?id='.$pid.'&view=taches')?>">Organiser les tâches</a></div>
<div class="card card-body"><?php require __DIR__.'/includes/views/decision_gantt.php';?></div>
<div class="card card-body" style="margin-top:20px"><h2>Dates & relations</h2><table class="table"><thead><tr><th>Tâche</th><th>Origine / responsable</th><th>Début prévu</th><th>Échéance</th><th>Dépendance</th></tr></thead><tbody><?php foreach($tachesAll as $t):?><tr><td><a href="<?=url('tache.php?id='.(int)$t['id'])?>">#<?=(int)$t['id']?> · <?=e($t['titre'])?></a></td><td><?php pfTaskLinks($t);?></td><td><?=e($t['date_debut']??'Non planifié')?></td><td><?=e($t['date_echeance']??'Non planifié')?></td><td><?php if(!empty($t['dependance_id'])):?><a href="<?=url('tache.php?id='.(int)$t['dependance_id'])?>">#<?=(int)$t['dependance_id']?></a><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div>
<?php require __DIR__.'/includes/footer.php';?>
