<?php
$pageTitle='Production & stock';$activePage='projets';require __DIR__.'/includes/bootstrap.php';require __DIR__.'/includes/ux_objects.php';require __DIR__.'/includes/stock/production_workflow.php';requerirConnexion();
$pid=(int)($_GET['projet_id']??0);$projet=pfLoadProject($pid);$db=getDB();productionSchema($db);
$q=$db->prepare('SELECT b.*,a.reference article FROM stock_boms b LEFT JOIN stock_articles a ON a.id=b.article_parent_id WHERE b.projet_id=?');$q->execute([$pid]);$boms=$q->fetchAll();
$q=$db->prepare('SELECT o.*,u.identifiant responsable,d.nom_fichier instruction FROM stock_production o JOIN utilisateurs u ON u.id=o.responsable_id JOIN documents d ON d.id=o.document_id WHERE o.projet_id=? ORDER BY o.id DESC');$q->execute([$pid]);$orders=$q->fetchAll();
$q=$db->prepare('SELECT l.*,a.reference article FROM stock_lots l JOIN stock_articles a ON a.id=l.article_id WHERE l.projet_id=? ORDER BY l.date_reception DESC');$q->execute([$pid]);$lots=$q->fetchAll();require __DIR__.'/includes/header.php';?>
<div class="page-header"><div><h1>Prototype, production & réception</h1><p class="text-muted">Nomenclatures, ordres et lots explicitement reliés au projet.</p></div><?php if(estAdmin()):?><a class="btn btn-primary" href="<?=url('stock_pilotage.php?tab=bom')?>">Gérer les nomenclatures</a><?php endif;?></div>
<div class="pf-metrics"><a class="pf-metric" href="#boms"><strong><?=count($boms)?></strong><span>Nomenclatures</span></a><a class="pf-metric" href="#orders"><strong><?=count($orders)?></strong><span>Ordres d’assemblage</span></a><a class="pf-metric" href="#lots"><strong><?=count($lots)?></strong><span>Lots reçus</span></a><a class="pf-metric" href="<?=url('documents_externes.php?projet_id='.$pid)?>"><strong>Dossier</strong><span>Instructions & preuves</span></a></div>
<section id="boms" class="card card-body"><h2>Nomenclatures</h2><?php foreach($boms as $b):?><div class="dash-task-row"><a href="<?=url(estAdmin()?'stock_production.php?bom_id='.(int)$b['id']:'stock_article.php?id='.(int)$b['article_parent_id'])?>"><?=e($b['reference'])?> · indice <?=e($b['version'])?></a><a href="<?=url('stock_article.php?id='.(int)$b['article_parent_id'])?>"><?=e($b['article'])?></a><span class="pf-tag"><?=e($b['statut'])?></span></div><?php endforeach;?><?php if(!$boms):?><p class="pf-empty">Aucune nomenclature liée à ce projet.</p><?php endif;?></section>
<section id="orders" class="card card-body" style="margin-top:20px"><h2>Ordres d’assemblage</h2><table class="table"><thead><tr><th>Ordre</th><th>Quantité</th><th>Date métier</th><th>Responsable</th><th>État</th><th>Instruction Nextcloud</th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td><?php if(estAdmin()):?><a href="<?=url('stock_production.php?bom_id='.(int)$o['bom_id'].'#order-'.(int)$o['id'])?>"><?=e($o['reference'])?></a><?php else:?><?=e($o['reference'])?><?php endif;?></td><td><?=(int)$o['quantite']?></td><td><?=e($o['date_metier'])?></td><td><a href="<?=url('personne.php?identifiant='.rawurlencode($o['responsable']).'&projet_id='.$pid)?>"><?=e($o['responsable'])?></a></td><td><span class="pf-tag"><?=e($o['statut'])?></span></td><td><a href="<?=url('documents_externes.php?projet_id='.$pid.'#document-'.(int)$o['document_id'])?>"><?=e($o['instruction'])?></a></td></tr><?php endforeach;?></tbody></table></section>
<section id="lots" class="card card-body" style="margin-top:20px"><div class="pf-section-head"><h2>Lots & réceptions</h2><a href="<?=url('stock_pilotage.php?tab=lots&projet_id='.$pid)?>">Journal de réception</a></div><table class="table"><thead><tr><th>Lot</th><th>Article</th><th>Réception</th><th>Quantité</th><th>État</th></tr></thead><tbody><?php foreach($lots as $l):?><tr><td><?=e($l['reference_lot'])?></td><td><a href="<?=url('stock_article.php?id='.(int)$l['article_id'])?>"><?=e($l['article'])?></a></td><td><?=e($l['date_reception'])?></td><td><?=e((string)$l['quantite_initiale'])?></td><td><span class="pf-tag"><?=e($l['statut'])?></span></td></tr><?php endforeach;?></tbody></table></section>
<?php require __DIR__.'/includes/footer.php';?>
