<?php
$pageTitle='Fiche S.T.';$activePage='projets';require __DIR__.'/includes/bootstrap.php';require __DIR__.'/includes/ux_objects.php';requerirConnexion();
$pid=(int)($_GET['projet_id']??0);$projet=pfLoadProject($pid);$specs=pfSpecs($pid);$st=null;$uid=(string)($_GET['uid']??'');$ref=(string)($_GET['st']??'');
foreach($specs['specs_techniques'] as $candidate)if($uid!==''?($candidate['uid']??'')===$uid:($candidate['id']??'')===$ref){$st=$candidate;break;}
if(!$st){setFlash('error','S.T. introuvable ou supprimée.');redirect('specifications.php?projet_id='.$pid);}
$sf=null;foreach($specs['fonctions'] as $f)if($f['id']===($st['sf']??''))$sf=$f;
$q=getDB()->prepare('SELECT * FROM taches WHERE projet_id=? ORDER BY id');$q->execute([$pid]);$tasks=array_values(array_filter($q->fetchAll(),fn($t)=>pfTaskStId($t)===$st['id'] && (estAdmin()||projectCanManage(getDB(),$pid,utilisateurCourant())||($t['assigne_a']??'')===utilisateurCourant()['identifiant'])));
$items=$specs['composants_st'][$st['id']]??[];$pageTitle=$st['id'];require __DIR__.'/includes/header.php';?>
<div class="page-header"><div><span class="pf-tag">SPÉCIFICATION TECHNIQUE</span><h1><?=e($st['id'])?></h1><p class="text-muted"><?=e($st['type'])?> · <a href="<?=url('specifications.php?projet_id='.$pid.'#'.rawurlencode($st['sf']??''))?>"><?=e($st['sf']??'')?></a></p></div><a class="btn btn-primary" href="<?=url('projet.php?id='.$pid.'&view=processus&step=2#'.rawurlencode($st['id']))?>">Modifier la définition</a></div>
<div class="pf-grid"><section class="card card-body"><h2>Définition</h2><p class="pf-technical-summary"><?=e($st['description'])?></p><?php if($sf):?><details style="margin-top:16px"><summary>Exigence parente · <?=e($sf['id'])?></summary><p><?=e($sf['description'])?></p></details><?php endif;?>
<?php if($st['type']==='S.T.x.x'):$target=null;foreach($specs['specs_techniques'] as $candidate)if(($candidate['uid']??'')===($st['st_reference_uid']??''))$target=$candidate;?><div class="r1b-info-box">Référence → <?php if($target):?><a href="<?=pfStUrl($pid,$target)?>"><?=e($target['id'])?> · <?=e($target['description'])?></a><?php else:?>Cible supprimée ou introuvable<?php endif;?></div><?php endif;?></section>
<section class="card card-body"><h2>Estimation amont · étape 2</h2><div class="pf-metrics"><div><span>Coût</span><p><strong><?=stTypeHasCost($st['type'])?e(pfMoney($st['cout_estime']??0,$st['cout_estime_taxe']??'HT')):'Sans coût d’achat'?></strong></p></div><div><span>Délai</span><p><strong><?=isset($st['delai_estime_jours'])?e((string)$st['delai_estime_jours']).' j':'Non renseigné'?></strong></p></div><div><span>Risque</span><p><?=pfRiskBadge($st['variation']??'')?></p></div></div><p class="text-muted">Ces valeurs restent celles des études initiales. Les composants ci-dessous proviennent de l’étape 4.</p></section></div>
<section class="card card-body" style="margin-top:20px"><div class="pf-section-head"><h2>Tâches associées · <?=count($tasks)?></h2><a href="<?=url('projet.php?id='.$pid.'&view=taches&tf_q='.rawurlencode($st['id']))?>">Voir dans le Kanban</a></div><?php foreach($tasks as $task):?><div class="dash-task-row"><a href="<?=url('tache.php?id='.(int)$task['id'])?>">#<?=(int)$task['id']?> · <?=e($task['titre'])?></a><div><?php pfTaskLinks($task);?></div><span class="pf-tag"><?=e(statutLabel($task['statut']))?></span></div><?php endforeach;?><?php if(!$tasks):?><p class="pf-empty">Aucune tâche associée visible pour votre compte.</p><?php endif;?></section>
<section class="card card-body" style="margin-top:20px"><div class="pf-section-head"><h2>Composants & besoins d’achat</h2><a href="<?=url('projet.php?id='.$pid.'&view=processus&step=4#'.rawurlencode($st['id']))?>">Modifier les composants</a></div><table class="table"><thead><tr><th>Ligne</th><th>Désignation</th><th>Référence / stock</th><th>Fournisseur</th><th>Qté</th><th>Coût</th><th>Délai</th></tr></thead><tbody><?php foreach($items as $it):$q=getDB()->prepare('SELECT id FROM stock_articles WHERE reference=? COLLATE NOCASE');$q->execute([$it['reference']??'']);$aid=(int)$q->fetchColumn();?><tr><td><?=e($it['id']??'')?></td><td><?=e($it['designation']??$it['assigne_a']??'')?></td><td><?php if($aid):?><a href="<?=url('stock_article.php?id='.$aid)?>"><?=e($it['reference'])?> ↗</a><?php else:?><?=e($it['reference']??'—')?><?php endif;?></td><td><?php if($aid):?><a href="<?=url('fournisseur.php?article_id='.$aid.'&projet_id='.$pid)?>"><?=e($it['fournisseur']??'Fournisseurs')?></a><?php else:?><?=e($it['fournisseur']??'—')?><?php endif;?></td><td><?=e((string)($it['quantite']??'—'))?></td><td><?=isset($it['cout_unitaire'])?e(pfMoney((float)($it['quantite']??1)*(float)$it['cout_unitaire'],$it['cout_unitaire_taxe']??'HT')):'—'?></td><td><?=e((string)($it['delai_estime_jours']??'—'))?></td></tr><?php endforeach;?></tbody></table><?php if(!$items):?><p class="pf-empty">Aucun composant défini à l’étape 4.</p><?php endif;?></section>
<div class="pf-links"><a href="<?=url('projet.php?id='.$pid.'&view=processus&step=5')?>">Achats du projet</a><a href="<?=url('documents_externes.php?projet_id='.$pid.'&st_uid='.rawurlencode($st['uid']))?>">Documents associés</a><a href="<?=url('planning.php?projet_id='.$pid)?>">Planning du projet</a></div>
<?php require __DIR__.'/includes/footer.php';?>
