<?php
$pageTitle='S.F. / S.T.';$activePage='projets';require __DIR__.'/includes/bootstrap.php';require __DIR__.'/includes/ux_objects.php';requerirConnexion();
$pid=(int)($_GET['projet_id']??0);$projet=pfLoadProject($pid);$specs=pfSpecs($pid);$data=ddConsolidate($specs);
$filter=(string)($_GET['risk']??'');require __DIR__.'/includes/header.php';?>
<div class="page-header"><div><h1>Exigences & spécifications</h1><p class="text-muted">Une définition commune, de l’estimation à la réalisation.</p></div><a class="btn btn-primary" href="<?=url('projet.php?id='.$pid.'&view=processus&step=2')?>">Modifier les S.T.</a></div>
<div class="pf-metrics"><a class="pf-metric" href="#specs"><strong><?=count($specs['fonctions'])?></strong><span>Spécifications fonctionnelles</span></a><a class="pf-metric" href="#specs"><strong><?=count($specs['specs_techniques'])?></strong><span>Spécifications techniques</span></a><a class="pf-metric" href="<?=url('projet.php?id='.$pid.'&view=processus&step=3#dd-cost')?>"><strong>Estimation</strong><span>Coûts & délais amont</span></a><a class="pf-metric" href="<?=url('specifications.php?projet_id='.$pid.'&risk=Fort')?>"><strong><?=count(array_filter($specs['specs_techniques'],fn($s)=>normalizeEstimationVariation($s['variation']??'')==='Fort'))?></strong><span>Risques forts</span></a></div>
<form class="pf-filter" method="get"><input type="hidden" name="projet_id" value="<?=$pid?>"><label for="specSearch">Rechercher</label><input id="specSearch" class="form-control" type="search" data-pf-filter="pf-spec-table" placeholder="S.T., type, description…"><label for="riskFilter">Risque</label><select id="riskFilter" class="form-control" name="risk" style="width:auto" onchange="this.form.submit()"><option value="">Tous</option><?php foreach(['Faible','Moyen','Fort'] as $r):?><option <?=$filter===$r?'selected':''?>><?=e($r)?></option><?php endforeach;?></select></form>
<div id="specs" class="card"><table class="table" id="pf-spec-table"><thead><tr><th>Exigence / S.T.</th><th>Description</th><th>Type</th><th>Coût amont</th><th>Délai</th><th>Risque</th><th>Explorer</th></tr></thead><tbody>
<?php foreach($specs['fonctions'] as $sf):?><tr id="<?=e($sf['id'])?>"><td colspan="7" class="pf-sf-title"><strong class="pf-object-id"><?=e($sf['id'])?></strong> <span class="pf-tag"><?=e($sf['indicateur']??'')?></span><p><?=e($sf['description'])?></p><small>Coûts amont consolidés : <?=e(pfMoney($data['bySf'][$sf['id']]['HT']??0,'HT'))?> · <?=e(pfMoney($data['bySf'][$sf['id']]['TTC']??0,'TTC'))?></small></td></tr>
<?php foreach($specs['specs_techniques'] as $st):if(($st['sf']??'')!==$sf['id']||($filter&&normalizeEstimationVariation($st['variation']??'')!==$filter))continue;?><tr><td><a class="pf-object-id" href="<?=pfStUrl($pid,$st)?>"><?=e($st['id'])?></a></td><td><?=e($st['description'])?></td><td><span class="pf-tag"><?=e($st['type'])?></span></td><td><?=stTypeHasCost($st['type'])?e(pfMoney($st['cout_estime']??0,$st['cout_taxe']??'HT')):'—'?></td><td><?=isset($st['delai_jours'])?e((string)$st['delai_jours']).' j':'Non renseigné'?></td><td><?=pfRiskBadge($st['variation']??'')?></td><td><a href="<?=pfStUrl($pid,$st)?>">Fiche & liens →</a></td></tr><?php endforeach;endforeach;?>
</tbody></table><?php if(!$specs['fonctions']):?><p class="pf-empty">Aucune exigence définie. Commencez par le cahier des charges.</p><?php endif;?></div>
<?php require __DIR__.'/includes/footer.php';?>
