<?php
$pageTitle='Comptage inventaire';$activePage='stock_pilotage';require_once __DIR__.'/includes/bootstrap.php';require_once __DIR__.'/includes/stock/inventory_workflow.php';requerirConnexion();requerirAdmin();runSchemaMigrations();$db=getDB();productionSchema($db);$id=(int)($_GET['id']??0);
$q=$db->prepare('SELECT i.*,e.chemin FROM stock_inventaires i LEFT JOIN stock_emplacements e ON e.id=i.emplacement_id WHERE i.id=?');$q->execute([$id]);$inv=$q->fetch();if(!$inv){setFlash('error','Inventaire introuvable.');redirect('stock_pilotage.php?tab=inventaires');}
if($_SERVER['REQUEST_METHOD']==='POST'){csrfRequire();try{if(($_POST['action']??'')==='compter')inventoryCount($db,$id,$_POST['comptee']??[],$_POST['notes']??[]);elseif(($_POST['action']??'')==='valider')inventoryValidate($db,$id,(int)utilisateurCourant()['id']);else throw new InvalidArgumentException('Action invalide.');setFlash('success','Inventaire enregistré.');redirect('stock_inventaire.php?id='.$id);}catch(Throwable $e){setFlash('error',$e->getMessage());}}
$q=$db->prepare('SELECT l.*,a.reference,e.chemin FROM stock_inventaire_lignes l JOIN stock_articles a ON a.id=l.article_id JOIN stock_emplacements e ON e.id=l.emplacement_id WHERE l.inventaire_id=? ORDER BY a.reference,e.chemin');$q->execute([$id]);$lines=$q->fetchAll();require __DIR__.'/includes/header.php';?>
<div class="page-header"><div><h1>Comptage <?=e($inv['code'])?></h1><p><?=e($inv['statut'])?> — <?=e($inv['chemin']??'Tous emplacements')?></p></div><a class="btn btn-secondary" href="<?=url('stock_pilotage.php?tab=inventaires')?>">Retour aux inventaires</a></div>
<div class="card" style="padding:1.25rem"><p>Le stock théorique est figé à l’ouverture. La validation refuse un stock modifié depuis le comptage. Les écarts de références sérialisées doivent être rapprochés avant validation ; ils ne sont pas ajustés automatiquement.</p>
<form method="post"><?=csrfField()?><input type="hidden" name="action" value="compter"><table class="table"><tr><th>Article</th><th>Emplacement</th><th>Théorique</th><th>Compté</th><th>Écart</th><th>Note</th></tr><?php foreach($lines as $l):?><tr><td><?=e($l['reference'])?></td><td><?=e($l['chemin'])?></td><td><?=e((string)$l['quantite_theorique'])?></td><td><input aria-label="Compté <?=e($l['reference'].' '.$l['chemin'])?>" name="comptee[<?=(int)$l['id']?>]" class="form-control" type="number" step="any" min="0" value="<?=e((string)($l['quantite_comptee']??''))?>" <?=$inv['statut']==='valide'?'disabled':''?> required></td><td><?=e((string)($l['ecart']??'—'))?></td><td><input aria-label="Note <?=e($l['reference'].' '.$l['chemin'])?>" name="notes[<?=(int)$l['id']?>]" class="form-control" value="<?=e($l['note']??'')?>" <?=$inv['statut']==='valide'?'disabled':''?>></td></tr><?php endforeach;?></table><?php if(!$lines):?><p>Aucun stock physique non nul dans ce périmètre à l’ouverture.</p><?php endif;?><?php if($inv['statut']==='ouvert'):?><button class="btn btn-primary">Enregistrer les comptages</button><?php endif;?></form>
<?php if($inv['statut']==='ouvert'):?><form method="post" style="margin-top:1rem"><?=csrfField()?><input type="hidden" name="action" value="valider"><p>La validation rapproche les écarts non sérialisés dans le journal de stock, puis ferme l’inventaire.</p><button class="btn btn-primary">Valider et rapprocher l’inventaire</button></form><?php else:?><p>Validé par #<?=(int)$inv['valide_par']?> le <?=e($inv['date_validation'])?>.</p><?php endif;?></div><?php require __DIR__.'/includes/footer.php';?>
