<?php
$pageTitle='Pilotage stock avancé'; $activePage='stock_pilotage';
require_once __DIR__.'/includes/bootstrap.php'; require_once __DIR__.'/includes/stock/stock_helpers.php';
requerirConnexion(); runSchemaMigrations(); $db=getDB();
$tabs=['reservations'=>'Réservations','lots'=>'Lots & réception','unites'=>'Unités / séries','bom'=>'BOM / nomenclatures','inventaires'=>'Inventaires','environnement'=>'Environnement'];
$tab=$_GET['tab']??'reservations'; if(!isset($tabs[$tab]))$tab='reservations';
$articles=$db->query("SELECT id,reference,designation FROM stock_articles ORDER BY reference")->fetchAll();
$projets=$db->query("SELECT id,nom FROM projets ORDER BY nom")->fetchAll();
$empl=$db->query("SELECT id,chemin FROM stock_emplacements WHERE actif=1 ORDER BY chemin")->fetchAll();
$fourn=$db->query("SELECT id,nom FROM stock_fournisseurs ORDER BY nom")->fetchAll();
function so($rows,$label){foreach($rows as $r)echo '<option value="'.(int)$r['id'].'">'.e($r[$label]).'</option>';}
if($_SERVER['REQUEST_METHOD']==='POST'){csrfRequire();$a=$_POST['action']??'';
 try{
  if($a==='reservation')$db->prepare("INSERT INTO stock_reservations(article_id,projet_id,quantite,emplacement_id,note) VALUES(?,?,?,?,?)")->execute([(int)$_POST['article_id'],(int)$_POST['projet_id'],(float)$_POST['quantite'],($_POST['emplacement_id']?:null),trim($_POST['note'])]);
  elseif($a==='lot')$db->prepare("INSERT INTO stock_lots(article_id,fournisseur_id,reference_lot,date_reception,quantite_initiale,cout_unitaire_ht,tva,statut,notes) VALUES(?,?,?,?,?,?,?,?,?)")->execute([(int)$_POST['article_id'],($_POST['fournisseur_id']?:null),trim($_POST['reference_lot']),($_POST['date_reception']?:date('Y-m-d')),(float)$_POST['quantite'],(float)$_POST['cout'],(float)$_POST['tva'],$_POST['statut'],trim($_POST['notes'])]);
  elseif($a==='unite')$db->prepare("INSERT INTO stock_unites(article_id,numero_serie,code_barres,uid_rfid,statut,emplacement_id,projet_id,date_acquisition,notes) VALUES(?,?,?,?,?,?,?,?,?)")->execute([(int)$_POST['article_id'],trim($_POST['numero_serie'])?:null,trim($_POST['code_barres'])?:null,trim($_POST['uid_rfid'])?:null,$_POST['statut'],($_POST['emplacement_id']?:null),($_POST['projet_id']?:null),($_POST['date_acquisition']?:null),trim($_POST['notes'])]);
  elseif($a==='bom')$db->prepare("INSERT INTO stock_boms(article_parent_id,projet_id,reference,designation,version,statut,notes) VALUES(?,?,?,?,?,?,?)")->execute([($_POST['article_parent_id']?:null),($_POST['projet_id']?:null),trim($_POST['reference']),trim($_POST['designation']),trim($_POST['version']),$_POST['statut'],trim($_POST['notes'])]);
  elseif($a==='inventaire')$db->prepare("INSERT INTO stock_inventaires(code,emplacement_id,statut,notes) VALUES(?,?,?,?)")->execute([trim($_POST['code']),($_POST['emplacement_id']?:null),'ouvert',trim($_POST['notes'])]);
  elseif($a==='env')$db->prepare("INSERT INTO stock_environnement(article_id,masse_g,matiere,substance_reglementee,dangereux,filiere_dechet,recyclage_possible,emballage,consignes) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(article_id) DO UPDATE SET masse_g=excluded.masse_g,matiere=excluded.matiere,substance_reglementee=excluded.substance_reglementee,dangereux=excluded.dangereux,filiere_dechet=excluded.filiere_dechet,recyclage_possible=excluded.recyclage_possible,emballage=excluded.emballage,consignes=excluded.consignes")->execute([(int)$_POST['article_id'],($_POST['masse_g']?:null),trim($_POST['matiere']),trim($_POST['substance']),isset($_POST['dangereux'])?1:0,trim($_POST['filiere']),isset($_POST['recyclable'])?1:0,trim($_POST['emballage']),trim($_POST['consignes'])]);
  setFlash('success','Enregistrement stock créé.');redirect('stock_pilotage.php?tab='.$tab);
 }catch(Throwable $e){setFlash('error','Erreur : '.$e->getMessage());}
}
require __DIR__.'/includes/header.php';?>
<div class="page-header"><div><h1><i class="fas fa-warehouse"></i> Pilotage stock avancé</h1><p class="text-muted">Traçabilité physique, projets, lots, séries, nomenclatures, inventaires et environnement.</p></div><a href="<?=url('stocks.php')?>" class="btn btn-secondary btn-sm">Catalogue</a></div>
<div class="card" style="padding:.75rem;margin:1rem 0;display:flex;gap:.5rem;flex-wrap:wrap"><?php foreach($tabs as $k=>$l):?><a class="btn <?=$tab===$k?'btn-primary':'btn-secondary'?> btn-sm" href="<?=url('stock_pilotage.php?tab='.$k)?>"><?=e($l)?></a><?php endforeach;?></div>
<?php if($tab==='reservations'): $rows=$db->query("SELECT r.*,a.reference,a.designation,p.nom projet,e.chemin FROM stock_reservations r JOIN stock_articles a ON a.id=r.article_id JOIN projets p ON p.id=r.projet_id LEFT JOIN stock_emplacements e ON e.id=r.emplacement_id ORDER BY r.id DESC")->fetchAll();?>
<div class="card" style="padding:1rem"><h2>Réservations projet</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="reservation"><div class="form-row"><select class="form-control" name="article_id" required><option value="">Article</option><?php so($articles,'reference');?></select><select class="form-control" name="projet_id" required><option value="">Projet</option><?php so($projets,'nom');?></select><input class="form-control" type="number" step=".01" min=".01" name="quantite" value="1"><select class="form-control" name="emplacement_id"><option value="">Emplacement</option><?php so($empl,'chemin');?></select><input class="form-control" name="note" placeholder="Note"><button class="btn btn-primary btn-sm">Réserver</button></div></form><table class="table"><tr><th>Article</th><th>Projet</th><th>Qté</th><th>Emplacement</th><th>Statut</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['reference'].' '.$r['designation'])?></td><td><?=e($r['projet'])?></td><td><?=e($r['quantite'])?></td><td><?=e($r['chemin']??'—')?></td><td><?=e($r['statut'])?></td></tr><?php endforeach;?></table></div>
<?php elseif($tab==='lots'): $rows=$db->query("SELECT l.*,a.reference,f.nom fournisseur FROM stock_lots l JOIN stock_articles a ON a.id=l.article_id LEFT JOIN stock_fournisseurs f ON f.id=l.fournisseur_id ORDER BY l.id DESC")->fetchAll();?>
<div class="card" style="padding:1rem"><h2>Lots & réception</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="lot"><div class="form-row"><select class="form-control" name="article_id" required><option value="">Article</option><?php so($articles,'reference');?></select><select class="form-control" name="fournisseur_id"><option value="">Fournisseur</option><?php so($fourn,'nom');?></select><input class="form-control" name="reference_lot" placeholder="N° lot"><input class="form-control" type="date" name="date_reception"><input class="form-control" type="number" step=".01" name="quantite" value="1"><input class="form-control" type="number" step=".01" name="cout" placeholder="Coût HT"><input class="form-control" type="number" step=".01" name="tva" placeholder="TVA %"><select class="form-control" name="statut"><option>quarantaine</option><option>libere</option><option>rejete</option></select></div><input class="form-control" name="notes" placeholder="Contrôle réception / notes"><button class="btn btn-primary btn-sm">Créer le lot</button></form><table class="table"><tr><th>Lot</th><th>Article</th><th>Fournisseur</th><th>Réception</th><th>Qté</th><th>Statut</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['reference_lot'])?></td><td><?=e($r['reference'])?></td><td><?=e($r['fournisseur']??'—')?></td><td><?=e($r['date_reception'])?></td><td><?=e($r['quantite_initiale'])?></td><td><?=e($r['statut'])?></td></tr><?php endforeach;?></table></div>
<?php elseif($tab==='unites'): $rows=$db->query("SELECT u.*,a.reference,e.chemin,p.nom projet FROM stock_unites u JOIN stock_articles a ON a.id=u.article_id LEFT JOIN stock_emplacements e ON e.id=u.emplacement_id LEFT JOIN projets p ON p.id=u.projet_id ORDER BY u.id DESC")->fetchAll();?>
<div class="card" style="padding:1rem"><h2>Unités sérialisées</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="unite"><div class="form-row"><select class="form-control" name="article_id" required><option value="">Article</option><?php so($articles,'reference');?></select><input class="form-control" name="numero_serie" placeholder="N° série"><input class="form-control" name="code_barres" placeholder="Code-barres"><input class="form-control" name="uid_rfid" placeholder="RFID"><select class="form-control" name="statut"><option value="en_stock">EN STOCK</option><option value="reserve">RÉSERVÉ</option><option value="affecte_projet">AFFECTÉ PROJET</option><option value="en_integration">EN INTÉGRATION</option><option value="integre">INTÉGRÉ</option><option value="demonte">DÉMONTÉ</option></select><select class="form-control" name="emplacement_id"><option value="">Emplacement</option><?php so($empl,'chemin');?></select><select class="form-control" name="projet_id"><option value="">Projet</option><?php so($projets,'nom');?></select><input class="form-control" type="date" name="date_acquisition"></div><input class="form-control" name="notes" placeholder="Notes"><button class="btn btn-primary btn-sm">Ajouter l'unité</button></form><table class="table"><tr><th>Article</th><th>Série</th><th>Statut</th><th>Emplacement</th><th>Projet</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['reference'])?></td><td><?=e($r['numero_serie']??'—')?></td><td><?=e($r['statut'])?></td><td><?=e($r['chemin']??'—')?></td><td><?=e($r['projet']??'—')?></td></tr><?php endforeach;?></table></div>
<?php elseif($tab==='bom'): $rows=$db->query("SELECT b.*,a.reference article,p.nom projet FROM stock_boms b LEFT JOIN stock_articles a ON a.id=b.article_parent_id LEFT JOIN projets p ON p.id=b.projet_id ORDER BY b.id DESC")->fetchAll();?>
<div class="card" style="padding:1rem"><h2>BOM / nomenclatures</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="bom"><div class="form-row"><input class="form-control" name="reference" placeholder="Référence BOM"><input class="form-control" name="designation" placeholder="Désignation"><input class="form-control" name="version" value="1.0"><select class="form-control" name="article_parent_id"><option value="">Article assemblé</option><?php so($articles,'reference');?></select><select class="form-control" name="projet_id"><option value="">Projet</option><?php so($projets,'nom');?></select><select class="form-control" name="statut"><option>brouillon</option><option>validee</option><option>obsolete</option></select></div><input class="form-control" name="notes" placeholder="Notes"><button class="btn btn-primary btn-sm">Créer la BOM</button></form><table class="table"><tr><th>Réf.</th><th>Désignation</th><th>Version</th><th>Article / Projet</th><th>Statut</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['reference'])?></td><td><?=e($r['designation'])?></td><td><?=e($r['version'])?></td><td><?=e(($r['article']??'').' '.($r['projet']??''))?></td><td><?=e($r['statut'])?></td></tr><?php endforeach;?></table></div>
<?php elseif($tab==='inventaires'): $rows=$db->query("SELECT i.*,e.chemin FROM stock_inventaires i LEFT JOIN stock_emplacements e ON e.id=i.emplacement_id ORDER BY i.id DESC")->fetchAll();?>
<div class="card" style="padding:1rem"><h2>Inventaires</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="inventaire"><div class="form-row"><input class="form-control" name="code" value="INV-<?=date('Ymd-His')?>" required><select class="form-control" name="emplacement_id"><option value="">Tous les emplacements</option><?php so($empl,'chemin');?></select><input class="form-control" name="notes" placeholder="Périmètre / notes"><button class="btn btn-primary btn-sm">Ouvrir l'inventaire</button></div></form><table class="table"><tr><th>Code</th><th>Date</th><th>Emplacement</th><th>Statut</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['code'])?></td><td><?=e($r['date_inventaire'])?></td><td><?=e($r['chemin']??'Tous')?></td><td><?=e($r['statut'])?></td></tr><?php endforeach;?></table></div>
<?php else: $rows=$db->query("SELECT se.*,a.reference,a.designation FROM stock_environnement se JOIN stock_articles a ON a.id=se.article_id ORDER BY a.reference")->fetchAll();?>
<div class="card" style="padding:1rem"><h2>Données environnementales articles</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="env"><div class="form-row"><select class="form-control" name="article_id" required><option value="">Article</option><?php so($articles,'reference');?></select><input class="form-control" type="number" step=".01" name="masse_g" placeholder="Masse g"><input class="form-control" name="matiere" placeholder="Matière"><input class="form-control" name="substance" placeholder="Substance réglementée"><input class="form-control" name="filiere" placeholder="Filière déchet"><input class="form-control" name="emballage" placeholder="Emballage"><label><input type="checkbox" name="dangereux"> Dangereux</label><label><input type="checkbox" name="recyclable"> Recyclable</label></div><textarea class="form-control" name="consignes" placeholder="Consignes environnement / fin de vie"></textarea><button class="btn btn-primary btn-sm">Enregistrer</button></form><table class="table"><tr><th>Article</th><th>Masse</th><th>Matière</th><th>Réglementé</th><th>Déchet</th><th>Recyclable</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['reference'].' '.$r['designation'])?></td><td><?=e($r['masse_g'])?> g</td><td><?=e($r['matiere'])?></td><td><?=e($r['substance_reglementee'])?></td><td><?=e($r['filiere_dechet'])?></td><td><?=$r['recyclage_possible']?'Oui':'Non'?></td></tr><?php endforeach;?></table></div>
<?php endif; require __DIR__.'/includes/footer.php';?>