<?php
$pageTitle='Pilotage stock avancé'; $activePage='stock_pilotage';
require_once __DIR__.'/includes/bootstrap.php'; require_once __DIR__.'/includes/stock/stock_helpers.php'; require_once __DIR__.'/includes/stock/lot_workflow.php'; require_once __DIR__.'/includes/stock/inventory_workflow.php'; require_once __DIR__.'/includes/stock/reservation_workflow.php';
requerirConnexion(); runSchemaMigrations(); $db=getDB(); stockLotSchema($db); reservationSchema($db);
$tabs=['reservations'=>'Réservations','lots'=>'Lots & réception','unites'=>'Unités / séries','bom'=>'BOM / nomenclatures','inventaires'=>'Inventaires','environnement'=>'Environnement'];
$tab=$_GET['tab']??'reservations'; if(!isset($tabs[$tab]))$tab='reservations';
$pid=(int)($_GET['projet_id']??0);$articleFilter=(int)($_GET['article_id']??0);
function pfStockRows(array $rows): array {global $pid,$articleFilter;return array_values(array_filter($rows,fn($r)=>(!$pid||((int)($r['projet_id']??0)===$pid))&&(!$articleFilter||((int)($r['article_id']??$r['article_parent_id']??0)===$articleFilter))));}
$stockContextQuery=($pid?'&projet_id='.$pid:'').($articleFilter?'&article_id='.$articleFilter:'');
$articles=$db->query("SELECT id,reference,designation FROM stock_articles ORDER BY reference")->fetchAll();
$projets=$db->query("SELECT id,nom FROM projets ORDER BY nom")->fetchAll();
$empl=$db->query("SELECT id,chemin FROM stock_emplacements WHERE actif=1 ORDER BY chemin")->fetchAll();
$fourn=$db->query("SELECT id,nom FROM stock_fournisseurs ORDER BY nom")->fetchAll();
function so($rows,$label){foreach($rows as $r)echo '<option value="'.(int)$r['id'].'">'.e($r[$label]).'</option>';}
if($_SERVER['REQUEST_METHOD']==='POST'){csrfRequire();$a=$_POST['action']??'';
 try{
  requerirAdmin();
  if($a==='reservation')reservationCreate($db,$_POST,(int)utilisateurCourant()['id']);
  elseif($a==='close_reservation')reservationClose($db,(int)($_POST['reservation_id']??0),(string)($_POST['statut']??''),(int)utilisateurCourant()['id'],trim((string)($_POST['motif']??'')));
  elseif($a==='lot')stockLotCreate($db,$_POST,(int)utilisateurCourant()['id']);
  elseif($a==='receive_lot')stockLotReceive($db,(int)($_POST['lot_id']??0),(int)($_POST['emplacement_id']??0),(int)($_POST['projet_id']??0)?:null,(int)utilisateurCourant()['id']);
  elseif($a==='unite')$db->prepare("INSERT INTO stock_unites(article_id,numero_serie,code_barres,uid_rfid,statut,emplacement_id,projet_id,date_acquisition,notes) VALUES(?,?,?,?,?,?,?,?,?)")->execute([(int)$_POST['article_id'],trim($_POST['numero_serie'])?:null,trim($_POST['code_barres'])?:null,trim($_POST['uid_rfid'])?:null,$_POST['statut'],($_POST['emplacement_id']?:null),($_POST['projet_id']?:null),($_POST['date_acquisition']?:null),trim($_POST['notes'])]);
  elseif($a==='bom')$db->prepare("INSERT INTO stock_boms(article_parent_id,projet_id,reference,designation,version,statut,notes) VALUES(?,?,?,?,?,?,?)")->execute([($_POST['article_parent_id']?:null),($_POST['projet_id']?:null),trim($_POST['reference']),trim($_POST['designation']),trim($_POST['version']),$_POST['statut'],trim($_POST['notes'])]);
  elseif($a==='inventaire'){requerirAdmin();inventoryOpen($db,trim($_POST['code']),(int)($_POST['emplacement_id']??0)?:null,trim($_POST['notes']));}
  elseif($a==='env') {
   $articleId=(int)($_POST['article_id']??0);
   $exists=$db->prepare('SELECT 1 FROM stock_articles WHERE id=?');$exists->execute([$articleId]);
   if(!$exists->fetchColumn())throw new InvalidArgumentException('Article introuvable.');
   $mass=trim((string)($_POST['masse_g']??''));
   if($mass!=='' && (!is_numeric($mass) || !is_finite((float)$mass) || (float)$mass<0))throw new InvalidArgumentException('La masse doit être positive ou nulle.');
   $db->prepare("INSERT INTO stock_environnement(article_id,masse_g,matiere,substance_reglementee,dangereux,filiere_dechet,recyclage_possible,emballage,consignes) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(article_id) DO UPDATE SET masse_g=excluded.masse_g,matiere=excluded.matiere,substance_reglementee=excluded.substance_reglementee,dangereux=excluded.dangereux,filiere_dechet=excluded.filiere_dechet,recyclage_possible=excluded.recyclage_possible,emballage=excluded.emballage,consignes=excluded.consignes")->execute([$articleId,$mass===''?null:(float)$mass,trim($_POST['matiere']),trim($_POST['substance']),isset($_POST['dangereux'])?1:0,trim($_POST['filiere']),isset($_POST['recyclable'])?1:0,trim($_POST['emballage']),trim($_POST['consignes'])]);
  }
  setFlash('success','Enregistrement stock créé.');redirect('stock_pilotage.php?tab='.$tab);
 }catch(Throwable $e){setFlash('error','Erreur : '.$e->getMessage());}
}
require __DIR__.'/includes/header.php';?>
<div class="page-header"><div><h1><i class="fas fa-warehouse"></i> Pilotage stock avancé</h1><p class="text-muted">Traçabilité physique, projets, lots, séries, nomenclatures, inventaires et environnement.</p></div><a href="<?=url('stocks.php')?>" class="btn btn-secondary btn-sm">Catalogue</a></div>
<div class="card" style="padding:.75rem;margin:1rem 0;display:flex;gap:.5rem;flex-wrap:wrap"><?php foreach($tabs as $k=>$l):?><a class="btn <?=$tab===$k?'btn-primary':'btn-secondary'?> btn-sm" href="<?=url('stock_pilotage.php?tab='.$k.$stockContextQuery)?>"><?=e($l)?></a><?php endforeach;?></div>
<?php if($tab==='reservations'): $rows=$db->query("SELECT r.*,a.reference,a.designation,p.nom projet,e.chemin FROM stock_reservations r JOIN stock_articles a ON a.id=r.article_id JOIN projets p ON p.id=r.projet_id LEFT JOIN stock_emplacements e ON e.id=r.emplacement_id ORDER BY r.id DESC")->fetchAll();$rows=pfStockRows($rows);?>
<div class="card" style="padding:1rem"><h2>Réservations projet</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="reservation"><div class="form-row"><select class="form-control" name="article_id" required><option value="">Article</option><?php so($articles,'reference');?></select><select class="form-control" name="projet_id" required><option value="">Projet</option><?php so($projets,'nom');?></select><input class="form-control" type="number" step=".01" min=".01" name="quantite" value="1"><select class="form-control" name="emplacement_id"><option value="">Emplacement</option><?php so($empl,'chemin');?></select><input class="form-control" name="note" placeholder="Note"><button class="btn btn-primary btn-sm">Réserver</button></div></form><table class="table"><tr><th>Article</th><th>Projet</th><th>Qté</th><th>Emplacement</th><th>Statut</th><th>Clôture / historique</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['reference'].' '.$r['designation'])?></td><td><a href="<?=url('production.php?projet_id='.(int)$r['projet_id'])?>"><?=e($r['projet'])?></a></td><td><?=e($r['quantite'])?></td><td><?=e($r['chemin']??'—')?></td><td><?=e($r['statut'])?></td><td><?php if(estAdmin() && $r['statut']==='active'):?><form method="post" class="closeReservationForm"><?=csrfField()?><input type="hidden" name="action" value="close_reservation"><input type="hidden" name="reservation_id" value="<?=(int)$r['id']?>"><label>Motif<input name="motif" class="form-control" required></label><label>Clôture<select name="statut" class="form-control"><option value="liberee">Libérer</option><option value="annulee">Annuler</option></select></label><button class="btn btn-secondary">Clore réservation #<?=(int)$r['id']?></button></form><?php endif; $h=$db->prepare('SELECT * FROM stock_reservation_historique WHERE reservation_id=? ORDER BY id');$h->execute([$r['id']]);foreach($h->fetchAll() as $event):?><p class="text-xs"><?=e($event['date_action'].' — #'.$event['utilisateur_id'].' — '.$event['action'].' — '.$event['details'])?></p><?php endforeach;?></td></tr><?php endforeach;?></table></div>
<?php elseif($tab==='lots'): $rows=$db->query("SELECT l.*,a.reference,f.nom fournisseur,(SELECT COUNT(*) FROM stock_mouvements m WHERE m.lot_id=l.id AND m.type='reception') entrees FROM stock_lots l JOIN stock_articles a ON a.id=l.article_id LEFT JOIN stock_fournisseurs f ON f.id=l.fournisseur_id ORDER BY l.id DESC")->fetchAll();$rows=pfStockRows($rows);?>
<div class="card" style="padding:1rem"><h2>Lots & réception</h2>
<p>Un lot en quarantaine ne devient pas disponible. Sa libération crée une seule entrée physique dans le journal. Les lots historiques libérés sans mouvement doivent être rapprochés explicitement.</p>
<?php if(estAdmin()):?><details class="pf-create"><summary>Enregistrer une réception</summary><form id="lotForm" method="post"><?=csrfField()?><input type="hidden" name="action" value="lot">
<div class="form-row"><label>Article<select class="form-control" name="article_id" required><option value="">Choisir</option><?php so($articles,'reference');?></select></label><label>Fournisseur<select class="form-control" name="fournisseur_id"><option value="">Non renseigné</option><?php so($fourn,'nom');?></select></label><label>Numéro de lot<input class="form-control" name="reference_lot" required maxlength="200"></label><label>Date de réception<input class="form-control" type="date" name="date_reception" required></label><label>Quantité<input class="form-control" type="number" step="any" min="0.000001" name="quantite" value="1" required></label><label>Coût unitaire HT<input class="form-control" type="number" step=".01" min="0" name="cout" value="0" required></label><label>TVA (%)<input class="form-control" type="number" step=".01" min="0" max="100" name="tva" value="20" required></label><label>Statut<select class="form-control" name="statut"><option value="quarantaine">Quarantaine</option><option value="libere">Libéré</option><option value="rejete">Rejeté</option></select></label></div>
<div class="form-row"><label>Emplacement de réception<select class="form-control" name="emplacement_id" required><option value="">Choisir</option><?php so($empl,'chemin');?></select></label><label>Projet<select class="form-control" name="projet_id"><option value="">Sans projet</option><?php so($projets,'nom');?></select></label></div>
<label>Contrôle réception / notes<input class="form-control" name="notes" maxlength="10000"></label><button class="btn btn-primary btn-sm">Créer le lot</button></form></details><?php endif;?>
<table class="table"><tr><th>Lot</th><th>Article</th><th>Fournisseur</th><th>Réception</th><th>Qté</th><th>Statut</th><th>Entrée physique</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['reference_lot'])?></td><td><a href="<?=url('stock_article.php?id='.(int)$r['article_id'])?>"><?=e($r['reference'])?></a></td><td><?php if(!empty($r['fournisseur_id'])):?><a href="<?=url('fournisseur.php?id='.(int)$r['fournisseur_id'])?>"><?=e($r['fournisseur'])?></a><?php else:?>—<?php endif;?></td><td><?=e($r['date_reception'])?></td><td><?=e($r['quantite_initiale'])?></td><td><?=e($r['statut'])?></td><td><?php if($r['entrees']):?>Enregistrée (<?= (int)$r['entrees']?> mouvement)<?php elseif(estAdmin() && in_array($r['statut'],['libere','quarantaine'],true)):?><form class="receiveLotForm" method="post"><?=csrfField()?><input type="hidden" name="action" value="receive_lot"><input type="hidden" name="lot_id" value="<?=(int)$r['id']?>"><label>Emplacement<select class="form-control" name="emplacement_id" required><option value="">Choisir</option><?php foreach($empl as $e):?><option value="<?=(int)$e['id']?>" <?=(int)($r['emplacement_id']??0)===(int)$e['id']?'selected':''?>><?=e($e['chemin'])?></option><?php endforeach;?></select></label><label>Projet<select class="form-control" name="projet_id"><option value="">Sans projet</option><?php foreach($projets as $p):?><option value="<?=(int)$p['id']?>" <?=(int)($r['projet_id']??0)===(int)$p['id']?'selected':''?>><?=e($p['nom'])?></option><?php endforeach;?></select></label><button class="btn btn-secondary btn-sm">Libérer et mettre en stock <?=e($r['reference_lot'])?></button></form><?php else:?>Non disponible<?php endif;?></td></tr><?php endforeach;?></table></div>
<?php elseif($tab==='unites'): $rows=$db->query("SELECT u.*,a.reference,e.chemin,p.nom projet FROM stock_unites u JOIN stock_articles a ON a.id=u.article_id LEFT JOIN stock_emplacements e ON e.id=u.emplacement_id LEFT JOIN projets p ON p.id=u.projet_id ORDER BY u.id DESC")->fetchAll();$rows=pfStockRows($rows);?>
<div class="card" style="padding:1rem"><h2>Unités sérialisées</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="unite"><div class="form-row"><select class="form-control" name="article_id" required><option value="">Article</option><?php so($articles,'reference');?></select><input class="form-control" name="numero_serie" placeholder="N° série"><input class="form-control" name="code_barres" placeholder="Code-barres"><input class="form-control" name="uid_rfid" placeholder="RFID"><select class="form-control" name="statut"><option value="en_stock">EN STOCK</option><option value="reserve">RÉSERVÉ</option><option value="affecte_projet">AFFECTÉ PROJET</option><option value="en_integration">EN INTÉGRATION</option><option value="integre">INTÉGRÉ</option><option value="demonte">DÉMONTÉ</option></select><select class="form-control" name="emplacement_id"><option value="">Emplacement</option><?php so($empl,'chemin');?></select><select class="form-control" name="projet_id"><option value="">Projet</option><?php so($projets,'nom');?></select><input class="form-control" type="date" name="date_acquisition"></div><input class="form-control" name="notes" placeholder="Notes"><button class="btn btn-primary btn-sm">Ajouter l'unité</button></form><table class="table"><tr><th>Article</th><th>Série</th><th>Statut</th><th>Emplacement</th><th>Projet</th></tr><?php foreach($rows as $r):?><tr><td><a href="<?=url('stock_article.php?id='.(int)$r['article_id'])?>"><?=e($r['reference'])?></a></td><td><?=e($r['numero_serie']??'—')?></td><td><?=e($r['statut'])?></td><td><?=e($r['chemin']??'—')?></td><td><?=e($r['projet']??'—')?></td></tr><?php endforeach;?></table></div>
<?php elseif($tab==='bom'): $rows=$db->query("SELECT b.*,a.reference article,p.nom projet FROM stock_boms b LEFT JOIN stock_articles a ON a.id=b.article_parent_id LEFT JOIN projets p ON p.id=b.projet_id ORDER BY b.id DESC")->fetchAll();$rows=pfStockRows($rows);?>
<div class="card" style="padding:1rem"><h2>BOM / nomenclatures</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="bom"><div class="form-row"><input class="form-control" name="reference" placeholder="Référence BOM"><input class="form-control" name="designation" placeholder="Désignation"><input class="form-control" name="version" value="1.0"><select class="form-control" name="article_parent_id"><option value="">Article assemblé</option><?php so($articles,'reference');?></select><select class="form-control" name="projet_id"><option value="">Projet</option><?php so($projets,'nom');?></select><select class="form-control" name="statut"><option>brouillon</option><option>validee</option><option>obsolete</option></select></div><input class="form-control" name="notes" placeholder="Notes"><button class="btn btn-primary btn-sm">Créer la BOM</button></form><table class="table"><tr><th>Réf.</th><th>Désignation</th><th>Version</th><th>Article / Projet</th><th>Statut</th></tr><?php foreach($rows as $r):?><tr><td><a href="<?=url('stock_production.php?bom_id='.(int)$r['id'])?>"><?=e($r['reference'])?></a></td><td><?=e($r['designation'])?></td><td><?=e($r['version'])?></td><td><?=e(($r['article']??'').' '.($r['projet']??''))?></td><td><?=e($r['statut'])?></td></tr><?php endforeach;?></table></div>
<?php elseif($tab==='inventaires'): $rows=$db->query("SELECT i.*,e.chemin FROM stock_inventaires i LEFT JOIN stock_emplacements e ON e.id=i.emplacement_id ORDER BY i.id DESC")->fetchAll();?>
<div class="card" style="padding:1rem"><h2>Inventaires</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="inventaire"><div class="form-row"><input class="form-control" name="code" value="INV-<?=date('Ymd-His')?>" required><select class="form-control" name="emplacement_id"><option value="">Tous les emplacements</option><?php so($empl,'chemin');?></select><input class="form-control" name="notes" placeholder="Périmètre / notes"><button class="btn btn-primary btn-sm">Ouvrir l'inventaire</button></div></form><table class="table"><tr><th>Code</th><th>Date</th><th>Emplacement</th><th>Statut</th></tr><?php foreach($rows as $r):?><tr><td><a href="<?=url('stock_inventaire.php?id='.(int)$r['id'])?>"><?=e($r['code'])?></a></td><td><?=e($r['date_inventaire'])?></td><td><?=e($r['chemin']??'Tous')?></td><td><?=e($r['statut'])?></td></tr><?php endforeach;?></table></div>
<?php else:
$rows=$db->query("SELECT se.*,a.reference,a.designation FROM stock_environnement se JOIN stock_articles a ON a.id=se.article_id ORDER BY a.reference")->fetchAll();
$edit=[];foreach($rows as $row)if((int)$row['article_id']===(int)($_GET['article_id']??0))$edit=$row;
?>
<div class="card" style="padding:1rem"><h2>Données environnementales articles</h2>
<?php if(estAdmin()):?><form method="post"><?=csrfField()?><input type="hidden" name="action" value="env">
<div class="form-row"><label>Article<select class="form-control" name="article_id" required><option value="">Article</option><?php foreach($articles as $article):?><option value="<?=(int)$article['id']?>" <?=(int)($edit['article_id']??0)===(int)$article['id']?'selected':''?>><?=e($article['reference'])?></option><?php endforeach;?></select></label>
<label>Masse (g)<input class="form-control" type="number" step=".01" min="0" name="masse_g" placeholder="Masse g" value="<?=e($edit['masse_g']??'')?>"></label>
<label>Matière<input class="form-control" name="matiere" placeholder="Matière" value="<?=e($edit['matiere']??'')?>"></label>
<label>Substance réglementée<input class="form-control" name="substance" placeholder="Substance réglementée" value="<?=e($edit['substance_reglementee']??'')?>"></label>
<label>Filière déchet<input class="form-control" name="filiere" placeholder="Filière déchet" value="<?=e($edit['filiere_dechet']??'')?>"></label>
<label>Emballage<input class="form-control" name="emballage" placeholder="Emballage" value="<?=e($edit['emballage']??'')?>"></label>
<label><input type="checkbox" name="dangereux" <?=!empty($edit['dangereux'])?'checked':''?>> Dangereux</label><label><input type="checkbox" name="recyclable" <?=!empty($edit['recyclage_possible'])?'checked':''?>> Recyclable</label></div>
<label>Consignes environnement / fin de vie<textarea class="form-control" name="consignes" placeholder="Consignes environnement / fin de vie"><?=e($edit['consignes']??'')?></textarea></label><button class="btn btn-primary btn-sm">Enregistrer</button></form><?php endif;?>
<div style="overflow-x:auto"><table class="table"><tr><th>Article</th><th>Masse</th><th>Matière</th><th>Réglementé</th><th>Déchet</th><th>Dangereux</th><th>Recyclable</th><th>Emballage / consignes</th><th>Fiche</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['reference'].' '.$r['designation'])?></td><td><?=$r['masse_g']===null?'—':e($r['masse_g']).' g'?></td><td><?=e($r['matiere'])?></td><td><?=e($r['substance_reglementee'])?></td><td><?=e($r['filiere_dechet'])?></td><td><?=$r['dangereux']?'Oui':'Non'?></td><td><?=$r['recyclage_possible']?'Oui':'Non'?></td><td><p><?=e($r['emballage'])?></p><p style="white-space:pre-wrap"><?=e($r['consignes'])?></p></td><td><?php if(estAdmin()):?><a href="<?=url('stock_pilotage.php?tab=environnement&article_id='.(int)$r['article_id'])?>">Modifier <?=e($r['reference'])?></a><?php endif;?></td></tr><?php endforeach;?></table></div></div>
<?php endif; require __DIR__.'/includes/footer.php';?>