<?php
require_once __DIR__.'/../includes/stock/production_workflow.php';
$db=new PDO('sqlite::memory:');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('PRAGMA foreign_keys=ON');
$db->exec("CREATE TABLE utilisateurs(id INTEGER PRIMARY KEY);INSERT INTO utilisateurs VALUES(1);
CREATE TABLE projets(id INTEGER PRIMARY KEY);INSERT INTO projets VALUES(1),(2);
CREATE TABLE documents(id INTEGER PRIMARY KEY,projet_id INTEGER);INSERT INTO documents VALUES(1,1),(2,2);
CREATE TABLE stock_articles(id INTEGER PRIMARY KEY,reference TEXT,designation TEXT,valeur_unitaire REAL,taxe TEXT,quantite_stock REAL DEFAULT 0,updated_at TEXT);INSERT INTO stock_articles(id,reference,valeur_unitaire,taxe) VALUES(1,'INPUT',10,'HT'),(2,'OUTPUT',10,'HT');
CREATE TABLE stock_fournisseurs(id INTEGER PRIMARY KEY);
CREATE TABLE stock_emplacements(id INTEGER PRIMARY KEY,actif INTEGER);INSERT INTO stock_emplacements VALUES(1,1),(2,1);
CREATE TABLE stock_lots(id INTEGER PRIMARY KEY,article_id INTEGER,fournisseur_id INTEGER,reference_lot TEXT,date_reception TEXT,quantite_initiale REAL,cout_unitaire_ht REAL,tva REAL,statut TEXT,notes TEXT);
CREATE TABLE stock_mouvements(id INTEGER PRIMARY KEY,article_id INTEGER,type TEXT,quantite REAL,emplacement_source_id INTEGER,emplacement_destination_id INTEGER,projet_id INTEGER,fournisseur_id INTEGER,lot_id INTEGER,unite_id INTEGER,reference_externe TEXT,note TEXT,user_id INTEGER);
CREATE TABLE stock_unites(id INTEGER PRIMARY KEY,article_id INTEGER,numero_serie TEXT UNIQUE,statut TEXT,emplacement_id INTEGER,projet_id INTEGER,date_acquisition TEXT,notes TEXT);
CREATE TABLE stock_boms(id INTEGER PRIMARY KEY,article_parent_id INTEGER,projet_id INTEGER,reference TEXT,version TEXT,statut TEXT);INSERT INTO stock_boms VALUES(1,2,1,'BOM','B','brouillon');
CREATE TABLE stock_bom_items(id INTEGER PRIMARY KEY,bom_id INTEGER,article_id INTEGER,quantite REAL,reference_position TEXT,notes TEXT);
CREATE TABLE stock_reservations(id INTEGER PRIMARY KEY,article_id INTEGER,projet_id INTEGER,quantite REAL,emplacement_id INTEGER,statut TEXT,date_fin TEXT,note TEXT);");
productionSchema($db);productionSchema($db);
function denied(callable $f):void {try{$f();}catch(InvalidArgumentException $e){return;}throw new RuntimeException('Action invalide acceptée');}
$line=['article_id'=>1,'quantite'=>1,'reference_position'=>'M1'];
denied(fn()=>productionBomSave($db,1,[array_merge($line,['quantite'=>-1])],'validee'));
denied(fn()=>productionBomSave($db,1,[$line,$line],'validee'));
denied(fn()=>productionBomSave($db,1,[array_merge($line,['article_id'=>2])],'validee'));
productionBomSave($db,1,[$line],'validee');
$p=['quantite'=>2,'reference'=>'OF1','date_metier'=>'2026-11-23','document_id'=>1,'responsable_id'=>1];
denied(fn()=>productionPlan($db,1,array_merge($p,['document_id'=>2]),1));
denied(fn()=>productionPlan($db,1,array_merge($p,['date_metier'=>'2026-02-30']),1));
$id=productionPlan($db,1,$p,1);
denied(fn()=>productionBomSave($db,1,[$line],'validee'));
$lot=stockLotCreate($db,['article_id'=>1,'emplacement_id'=>1,'projet_id'=>1,'reference_lot'=>'L1','date_reception'=>'2026-11-01','quantite'=>2,'statut'=>'quarantaine'],1);
$complete=['destination_id'=>2,'series'=>"S1\nS2",'resultat'=>'Contrôle conforme fictif','lot'=>[1=>$lot],'source'=>[1=>1]];
denied(fn()=>productionComplete($db,$id,$complete,1));
stockLotReceive($db,$lot,1,1,1);
denied(fn()=>productionComplete($db,$id,array_merge($complete,['source'=>[1=>2]]),1));
denied(fn()=>productionComplete($db,$id,array_merge($complete,['series'=>"S1\nS1"]),1));
$db->exec("INSERT INTO stock_reservations(id,article_id,projet_id,quantite,emplacement_id,statut) VALUES(1,1,2,1,1,'active')");denied(fn()=>productionComplete($db,$id,$complete,1));$db->exec("UPDATE stock_reservations SET statut='liberee'; INSERT INTO stock_reservations(id,article_id,projet_id,quantite,emplacement_id,statut) VALUES(2,1,1,2,1,'active')");
productionComplete($db,$id,$complete,1);productionComplete($db,$id,$complete,1);
if(productionQuantity($db,1,1)!==0.0||productionQuantity($db,2,2)!==2.0||$db->query('SELECT COUNT(*) FROM stock_unites')->fetchColumn()!=2||$db->query('SELECT COUNT(*) FROM stock_production_composants')->fetchColumn()!=2||$db->query('SELECT COUNT(*) FROM stock_mouvements')->fetchColumn()!=5)throw new RuntimeException('Stock, généalogie ou idempotence incorrects');
if($db->query("SELECT statut FROM stock_reservations WHERE id=2")->fetchColumn()!=='consommee')throw new RuntimeException('Réservation propre non consommée');
$p['reference']='OF2';$id2=productionPlan($db,1,$p,1);denied(fn()=>productionComplete($db,$id2,$complete,1));
if($db->query('SELECT COUNT(*) FROM stock_unites')->fetchColumn()!=2||$db->query("SELECT statut FROM stock_production WHERE id=$id2")->fetchColumn()!=='planifie')throw new RuntimeException('Rollback incorrect');
echo "OK : BOM, documents du projet, lots, disponibilité, réservations, séries, généalogie, atomicité et idempotence production\n";
