<?php
$d=ddConsolidate($specs);
$sourceLink=static fn($source):string => url('projet.php?id='.$id.'&view=processus&step='.$source);
$cdcLink=url('cahier_form.php?projet_id='.$id.'&step=1&return_view=processus&return_step=3');
$costText=ddCostSummary($d);
$critical=count(array_filter($d['risks'],static fn($r)=>$r['level']==='Critique'));
?>
<div class="dd-dashboard" id="decision-dashboard">
 <div class="dd-intro"><div><p class="dd-eyebrow">ÉTAPES 1 ET 2 · BASE DE DÉCISION</p><h4>Pouvons-nous raisonnablement poursuivre ?</h4><p>Estimations amont enregistrées, recalculées après correction des étapes 1/2. Chaque nouvelle décision conserve sa propre copie des sources.</p></div><span class="dd-badge <?= $critical?'dd-critical':'dd-unknown' ?>"><?= $critical?'Défavorable : écart constaté':'Informations à confirmer' ?></span></div>
 <div class="dd-kpis">
 <a class="dd-kpi" href="#dd-capacity"><span class="dd-eyebrow">CAPACITÉ</span><strong><?=count($d['groups'])?> domaines</strong><span><?=count($d['sfs'])?> S.F. · <?=count($d['lines'])?> S.T.</span><span class="dd-badge <?= $d['capacityComplete']?'pf-tone-success':'dd-unknown' ?>"><?= $d['capacityConfirmed'] ?> / <?= count($d['capacity']) ?> S.T. confirmées</span></a>
 <a class="dd-kpi" href="#dd-cost"><span class="dd-eyebrow">COÛT ESTIMÉ</span><strong id="dd-cost-total"><?=e($costText)?></strong><span><?= $d['lotHT']===null?'Base S.T. pour un équipement':'Périmètre : '.e((string)$d['qty']).' équipement(s)' ?></span><span class="dd-badge <?= $d['margin']!==null&&$d['margin']<0?'dd-critical':'dd-unknown' ?>"><?= $d['margin']===null?'Comparaison impossible':($d['margin']<0?'Dépassement estimé':'Solde estimé avant compléments') ?></span></a>
 <a class="dd-kpi" href="#dd-time"><span class="dd-eyebrow">DÉLAI ESTIMÉ</span><strong id="dd-max-delay"><?=e(ddDelaySummary($d))?></strong><span><?= $d['delayIncompleteCount'] ? 'Plus long délai connu : '.e(ddDays($d['maxDelay'])).' · '.$d['delayIncompleteCount'].' délai(s) inconnu(s)' : 'Plus long délai élémentaire' ?></span><span class="dd-badge dd-unknown">Délai global non déterminé</span></a>
 <a class="dd-kpi" href="#dd-risks"><span class="dd-eyebrow">RISQUE / INCERTITUDE INITIAL</span><strong><?=$d['riskCounts']['Fort']?> Fort</strong><span><?=$d['riskCounts']['Faible']?> Faible · <?=$d['riskCounts']['Moyen']?> Moyen</span><span class="dd-badge dd-unknown"><?=$d['riskCounts']['Non renseigné']?> non renseigné(s)</span></a>
 </div>
 <nav class="dd-nav" aria-label="Sections de la synthèse"><a href="#dd-capacity">Capacité</a><a href="#dd-cost">Coût estimé</a><a href="#dd-time">Délai estimé</a><a href="#dd-risks">Risque / Incertitude</a><a href="#dd-missing">Informations à confirmer</a><a href="#dd-summary">Synthèse</a></nav>
 <section id="dd-capacity" class="dd-section"><div class="dd-section-head"><h4>Analyse capacité</h4><a href="<?=e($sourceLink(2))?>">Revoir les études</a></div><p>Une S.T. est confirmée lorsque tous ses champs applicables de l’Étape 2 sont renseignés et enregistrés avec des valeurs connues. Les champs de coût ne concernent pas Logiciel et 3D. Une référence S.T. suit la confirmation de sa source.</p><div class="dd-cap-grid">
 <?php foreach($d['groups'] as $type=>$g):?><article class="dd-domain"><strong><?=e($type)?></strong><p><?=$g['count']?> S.T. identifiée(s)</p><span class="dd-badge <?= $d['capacityGroups'][$type]['confirmed']===$g['count']?'pf-tone-success':'dd-unknown' ?>"><?= $d['capacityGroups'][$type]['confirmed'] ?> / <?= $g['count'] ?> S.T. confirmées</span><?php foreach($d['lines'] as $line):if(($line['type']??'')!==$type)continue;?><p><a href="<?=e($sourceLink(2))?>"><?=e($line['id'].' · '.$line['sf'])?></a> — <?=e($line['description']??'')?> <span class="dd-badge <?= $line['capacity_confirmed']?'pf-tone-success':'dd-unknown' ?>"><?= $line['capacity_confirmed']?'Confirmée':'À compléter' ?></span><?php if(!$line['capacity_confirmed']):?><small>Champs manquants : <?=e(implode(', ', $line['capacity_missing']))?></small><?php endif;?></p><?php endforeach;?></article><?php endforeach;?></div>
 <?php if($d['references']):?><details class="dd-details"><summary>Relations S.T. (<?=count($d['references'])?>) — sans double comptage</summary><?php foreach($d['references'] as $ref):?><p><?=e($ref['id'])?> → <?=e($ref['target']??'Référence invalide')?> · <?= $ref['confirmed']?'Confirmée':'À compléter : '.e(implode(', ', $ref['missing'])) ?></p><?php endforeach;?></details><?php endif;?></section>
 <section id="dd-cost" class="dd-section"><div class="dd-section-head"><h4>Analyse des coûts estimés</h4><a href="<?=e($sourceLink(2))?>">Détail des coûts S.T.</a></div>
 <div class="dd-budget"><div><small>Budget cible du CDC</small><strong><?= $d['budget']===null?'Non renseigné':e(ddMoney($d['budget'],$d['targets']['taxe']??'HT')) ?></strong><p>Cible structurée de l’Étape 1</p></div><div><small>Coût estimé du périmètre</small><strong><?=e($costText)?></strong><p><?= $d['costIncompleteCount'] ? 'Estimation totale impossible tant que des coûts restent inconnus.' : 'Totaux S.T. × quantité du périmètre du CDC' ?></p></div><div><small><?= $d['margin']!==null && $d['margin']<0?'Dépassement':'Solde avant compléments' ?></small><strong class="<?= $d['margin']!==null && $d['margin']<0?'dd-red':'' ?>"><?= $d['margin']===null?'Comparaison impossible':e(ddMoney(abs($d['margin']))) ?></strong><?php if($d['margin']!==null && $d['budgetHT']>0):?><p><?=number_format(100*abs($d['margin'])/$d['budgetHT'],1,',',' ')?> % de l’enveloppe</p><?php endif;?></div></div>
 <?php if($d['margin']!==null && $d['budgetHT']>0):?><div class="dd-track dd-budget-track" aria-label="Base S.T. rapportée au budget"><span style="width:<?=min(100,round(100*$d['lotHT']/$d['budgetHT'],2))?>%" class="<?= $d['margin']<0?'dd-over':'' ?>"></span></div><p class="dd-muted">Couverture S.T. : <?=number_format(100*$d['lotHT']/$d['budgetHT'],1,',',' ')?> % du budget. Le solde ne constitue pas une marge finale.</p><?php else:?><p class="dd-alert"><?= $d['costIncompleteCount'] ? 'Coût estimé incomplet : '. $d['costIncompleteCount'].' coût(s) inconnu(s) — comparaison budgétaire impossible.' : 'Budget cible ou quantité ou rapprochement fiscal non renseigné — comparaison impossible.' ?></p><?php endif;?>
 <p class="dd-method">Calcul : totaux estimés (quantité S.T. × coût unitaire) de l’Étape 2, chaque S.T. comptée une fois. Logiciel et 3D exclus des achats. <?= $d['vat']===null?'HT et TTC restent séparés, sans conversion supposée.':'Conversion TTC / (1 + '.e((string)$d['vat']).' / 100), taux déclaré dans le CDC.' ?> Aucun coût de tâche n’est ajouté une seconde fois.</p>
 <div class="dd-two"><div><h5>Répartition par type · un équipement</h5><?php $scale=max(array_merge([1],array_map(static fn($g)=>$g['HT']+$g['TTC'], $d['groups']),array_map(static fn($g)=>$g['HT']+$g['TTC'], $d['bySf']))); foreach($d['groups'] as $type=>$g): if(!ddHasCost($type))continue; ?><div class="dd-cost-row"><div><strong><?=e($type)?></strong><span><?=e(ddCostSubtotal($g))?></span></div><div class="dd-track"><span style="width:<?=round(100*$g['HT']/$scale,2)?>%"></span><span class="dd-ttc" style="width:<?=round(100*$g['TTC']/$scale,2)?>%"></span></div></div><?php endforeach;?><p class="dd-muted">Bleu : HT · violet : TTC. Montants séparés ; segments non additionnés fiscalement.</p></div>
 <div><h5>Coûts par sous-fonction · un équipement</h5><?php foreach($d['bySf'] as $sf=>$g):?><div class="dd-cost-row"><div><a href="<?=e($sourceLink(2))?>"><?=e($sf)?></a><span><?=e(ddCostSubtotal($g))?></span></div><div class="dd-track"><span style="width:<?=min(100,round(100*$g['HT']/$scale,2))?>%"></span><span class="dd-ttc" style="width:<?=min(100,round(100*$g['TTC']/$scale,2))?>%"></span></div><small><?=e($d['sfs'][$sf]['description']??'S.F. absente')?></small></div><?php endforeach;?></div></div>
 </section>
 <section id="dd-time" class="dd-section"><div class="dd-section-head"><h4>Analyse des délais estimés</h4><a href="<?=e($sourceLink(2))?>">Revoir les délais S.T.</a></div><div class="dd-budget"><div><small>Objectif Étape 1</small><strong><?=e(ddDays($d['targetDays']))?></strong></div><div><small>Plus long délai estimé Étape 2</small><strong><?=e(ddDelaySummary($d))?></strong></div><div><small>Écart élémentaire / objectif</small><strong><?= $d['delayIncompleteCount']>0||$d['targetDays']===null||$d['maxDelay']===null?'Impossible à déterminer':e(ddDays(abs($d['targetDays']-$d['maxDelay']))).($d['maxDelay']>$d['targetDays']?' de dépassement':' sous l’objectif') ?></strong></div></div>
 <?php if($d['delayIncompleteCount']):?><p class="dd-alert"><?= $d['delayIncompleteCount'] ?> délai(s) inconnu(s). Le maximum des délais connus est <?=e(ddDays($d['maxDelay']))?> ; il ne permet pas de conclure sur les éléments inconnus.</p><?php endif;?>
 <p class="dd-muted">Durées élémentaires comparées, sans supposer un départ simultané. Elles ne sont ni additionnées ni remplacées par un planning ultérieur.</p>
 <?php $delayLines=$d['lines'];usort($delayLines,static fn($a,$b)=>($b['delay']??-1)<=>($a['delay']??-1));foreach($delayLines as $line):?><div class="dd-time-row"><a href="<?=e($sourceLink(2))?>"><?=e($line['id'].' · '.$line['type'])?></a><div class="dd-track"><span style="width:<?=$line['delay']!==null&&$d['maxDelay']>0?round(100*$line['delay']/$d['maxDelay'],2):0?>%" class="dd-long"></span></div><strong><?=e($line['delay_unknown'] ? 'Inconnu' : ddDays($line['delay']))?></strong></div><?php endforeach;?>
 <div class="dd-alert">Délai global impossible à déterminer : parallélisation, intégration et chemin critique ne sont pas établis dans les études initiales.</div><details class="dd-details"><summary>Objectifs et planning textuel Étape 1</summary><p class="dd-pre"><?=e(($specs['delais']??'')?:'Non renseigné')?></p></details></section>
 <section id="dd-risks" class="dd-section"><h4>Risque / Incertitude initial — Étape 2</h4>
 <?php foreach($d['riskCounts'] as $level=>$count):?><div class="dd-bar-row"><span><?=e($level)?></span><div class="dd-track"><span class="dd-risk-<?= $level==='Fort'?'high':($level==='Faible'?'low':'medium') ?>" style="width:<?=count($d['lines'])?round(100*$count/count($d['lines']),2):0?>%"></span></div><strong><?=$count?></strong></div><?php endforeach;?>
 <div class="dd-risk-grid"><?php foreach($d['risks'] as $r):?><article class="dd-risk"><span class="dd-badge <?=in_array($r['level'],['Critique','Fort'],true)?'dd-critical':'dd-unknown'?>"><?=e($r['impact'].' · '.$r['level'])?></span><h5><?=e($r['subject'])?></h5><p><?=e($r['detail'])?></p><p><?=e($r['action'])?></p><a href="<?=e($sourceLink($r['source']))?>">Corriger Étape <?=$r['source']?></a></article><?php endforeach;?></div></section>
 <section id="dd-missing" class="dd-section"><h4>Informations à confirmer <span class="dd-count"><?=count($d['missing'])?></span></h4><p>Une valeur absente reste inconnue et ne constitue pas un résultat favorable.</p><div class="dd-missing"><?php foreach($d['missing'] as $m):?><a href="<?=e($m['source']===1?$cdcLink:$sourceLink(2))?>"><strong><?=e($m['subject'])?></strong><small><?=e($m['action'])?></small><span>→</span></a><?php endforeach;?></div></section>
 <details class="dd-details"><summary>Besoin et contraintes — Étape 1</summary><?php foreach(['objectifs'=>'Objectifs et contexte','resultats_attendus'=>'Hors périmètre','cas_usage'=>'Contraintes','profils_utilisateurs'=>'Utilisateurs','livrables_attendus'=>'Livrables'] as $key=>$label):?><h5><?=e($label)?></h5><p class="dd-pre"><?=e(($specs[$key]??'')?:'Non renseigné')?></p><?php endforeach;?></details>
 <section id="dd-summary" class="dd-section dd-summary"><p class="dd-eyebrow">SYNTHÈSE AVANT DÉCISION</p><h4><?= $critical?'Écart défavorable identifié':'Informations à confirmer avant décision' ?></h4><div class="dd-summary-grid"><div><small>CAPACITÉ</small><strong><?=count($d['groups'])?> domaines · <?=count($d['lines'])?> S.T.</strong><p><?= $d['capacityConfirmed'] ?> / <?= count($d['capacity']) ?> S.T. confirmées selon les champs enregistrés à l’Étape 2.</p></div><div><small>COÛT ESTIMÉ</small><strong><?=e($costText)?></strong><p>Cible <?= $d['budget']===null?'non renseignée':e(ddMoney($d['budget'],$d['targets']['taxe']??'HT')) ?> ; <?= $d['margin']===null?'écart impossible à déterminer':e(ddMoney(abs($d['margin']))).($d['margin']<0?' de dépassement':' de solde avant compléments') ?>.</p></div><div><small>DÉLAI ESTIMÉ</small><strong><?=e(ddDelaySummary($d))?> · élémentaire</strong><p>Objectif <?=e(ddDays($d['targetDays']))?> ; délai global non déterminé.</p></div><div><small>RISQUE / INCERTITUDE</small><strong><?=$d['riskCounts']['Faible']?> Faible · <?=$d['riskCounts']['Moyen']?> Moyen · <?=$d['riskCounts']['Fort']?> Fort</strong><p><?=$d['riskCounts']['Non renseigné']?> non renseigné(s).</p></div></div><p><strong><?=count($d['missing'])?> informations à confirmer.</strong> La décision GO / NO GO reste humaine. Précisez les S.F., S.T. ou données amont à corriger dans le motif de refus.</p><p><a href="<?=e($sourceLink(1))?>">Corriger Étape 1</a> · <a href="<?=e($sourceLink(2))?>">Corriger Étape 2</a></p>
 <?php if($lastDecision):?><p>Dernière décision : <strong><?=e($lastDecision['decision'])?></strong> · <?=e($lastDecision['date_decision'])?> UTC · <?=e($lastDecision['identifiant'])?></p><p><?=empty($lastDecision['snapshot_json'])?'Ancienne décision : état des sources non conservé, aucune reconstruction rétroactive.':'Sources de cette décision conservées dans l’historique, indépendamment de la synthèse actuelle.'?></p><?php endif;?><p>Les nouvelles décisions conservent le besoin, les cibles, les S.F. et les S.T. des étapes 1/2 dans l’historique.</p></section>
</div>
