<?php
$d=ddConsolidate($specs,$tachesAll,$decisionUsers);
$sourceLink=static function($source)use($id):string{return url('projet.php?id='.$id.'&view='.($source==='tasks'?'taches':'processus&step='.$source));};
$cdcLink=url('cahier_form.php?projet_id='.$id.'&step=1&return_view=processus&return_step=3');
$capText=count($d['lines']).' S.T. · '.count($d['assigned']).' ressources';
$costText=$d['lotHT']===null?ddMoney($d['totals']['HT']).($d['totals']['TTC']>0?' + '.ddMoney($d['totals']['TTC'],'TTC'):''):ddMoney($d['lotHT']);
$critical=count(array_filter($d['risks'],static fn($r)=>$r['level']==='Critique'));
?>
<div class="dd-dashboard" id="decision-dashboard">
 <div class="dd-intro"><div><p class="dd-eyebrow">VALIDATION CAPACITÉ / COÛT / DÉLAI</p><h4>Les éléments pour décider</h4><p>Consolidation des données enregistrées · mise à jour à chaque ouverture</p></div><span class="dd-badge <?= $critical?'dd-critical':'dd-unknown' ?>"><?= $critical?'Écart critique constaté':'Décision avec réserves à confirmer' ?></span></div>
 <div class="dd-kpis">
  <a class="dd-kpi" href="#dd-capacity"><span class="dd-kpi-icon">◎</span><span class="dd-eyebrow">CAPACITÉ</span><strong><?= count($d['assigned']) ?> ressources</strong><span><?= count($d['lines']) ?> S.T. · <?= count($tachesAll) ?> tâches</span><span class="dd-badge dd-unknown">Disponibilités à confirmer</span></a>
  <a class="dd-kpi" href="#dd-cost"><span class="dd-kpi-icon">€</span><span class="dd-eyebrow">COÛT · BASE S.T.</span><strong id="dd-cost-total"><?= e($costText) ?></strong><span><?= $d['qty']!==null?e((string)$d['qty']).' équipement(s)':'Quantité non renseignée' ?> · postes complémentaires exclus</span><span class="dd-badge <?= $d['margin']!==null && $d['margin']<0?'dd-critical':'dd-watch' ?>"><?= $d['margin']!==null && $d['margin']<0?'Budget dépassé':'Estimation partielle' ?></span></a>
  <a class="dd-kpi" href="#dd-time"><span class="dd-kpi-icon">◷</span><span class="dd-eyebrow">DÉLAI GLOBAL</span><strong>À confirmer</strong><span>Plus long délai S.T. : <?= e(ddDays($d['maxDelay'])) ?></span><span class="dd-badge dd-unknown">Planning incomplet</span></a>
 </div>
 <nav class="dd-nav" aria-label="Sections de la synthèse"><a href="#dd-capacity">Capacité</a><a href="#dd-cost">Coût</a><a href="#dd-time">Délai</a><a href="#dd-risks">Vigilances</a><a href="#dd-summary">Décision</a></nav>
 <section id="dd-capacity" class="dd-section"><div class="dd-section-head"><h4>Capacité & ressources</h4><a href="<?=e($sourceLink('tasks'))?>">Voir / affecter les tâches</a></div>
 <p class="dd-muted">Affectations constatées, sans présumer de la disponibilité ni d’un taux de capacité.</p>
 <div class="dd-cap-grid">
 <?php foreach($d['groups'] as $type=>$g): ?><article class="dd-domain"><div><strong><?=e($type)?></strong><span class="dd-badge <?= $g['assigned']===$g['count']?'dd-ok':'dd-unknown' ?>"><?= $g['assigned'] ?>/<?= $g['count'] ?> S.T. affectées</span></div><div class="dd-track"><span style="width:<?= $g['count']?round(100*$g['assigned']/$g['count'],2):0 ?>%"></span></div><p><?= in_array($type,['Logiciel','3D'],true)?'Réalisation interne à confirmer':($type==='Prestataire'?'Prestation externe à confirmer':'Étude / achat selon la définition') ?></p>
 <?php foreach($g['people'] as $ident=>$u): ?><p><strong><?=e($u['nom_affiche']??$ident)?></strong> · <?=e($u['fonction']??'fonction non renseignée')?></p><small><?=e($u['competences']??'Compétences non renseignées')?></small><?php endforeach; ?>
 <?php if(!$g['people']):?><p>Aucune ressource affectée aux études.</p><?php endif; ?><small>Disponibilité : non renseignée</small></article><?php endforeach; ?>
 </div>
 <div class="dd-two"><div><h5>Répartition des tâches</h5><p class="dd-muted">Nombre de tâches, toutes phases du projet. Ce graphique ne mesure pas une charge en heures.</p>
 <?php $maxTasks=max(array_merge([1],array_map('count',$d['assigned']))); foreach($d['assigned'] as $who=>$ts): ?><div class="dd-bar-row"><span><?=e($d['byUser'][$who]['nom_affiche']??$who)?></span><div class="dd-track"><span style="width:<?=round(100*count($ts)/$maxTasks,2)?>%"></span></div><strong><?=count($ts)?></strong></div><?php endforeach; ?>
 <p><?=count($d['unassigned'])?> tâche(s) sans responsable. Plafond de charge du CDC : <?= $d['targets']['charge']??null?e((string)$d['targets']['charge']).' jours-personnes':'non renseigné' ?> ; charge estimée structurée non disponible.</p>
 </div><div><h5>Traçabilité des études</h5><?php foreach($d['lines'] as $line):?><p class="dd-study"><a href="<?=e($sourceLink(2))?>"><?=e($line['id'])?></a> · <?=e($line['type']??'')?><?php if($line['task']):?> · <a href="<?=url('tache.php?id='.(int)$line['task']['id'])?>">Tâche #<?=(int)$line['task']['id']?></a> · <?=e($line['who']?:'Non affectée')?><?php else:?> · Tâche non générée<?php endif;?></p><?php endforeach;?></div></div>
 </section>
 <section id="dd-cost" class="dd-section"><div class="dd-section-head"><h4>Analyse financière</h4><a href="<?=e($sourceLink(2))?>">Détail des coûts S.T.</a></div>
 <div class="dd-budget"><div><small>Budget cible du CDC</small><strong><?= $d['budget']===null?'Non renseigné':e(ddMoney($d['budget'],$d['targets']['taxe']??'HT')) ?></strong><p><?=e($d['targets']['perimetre']??'Périmètre à confirmer')?></p></div><div><small>Base estimée pour le périmètre</small><strong><?=e($costText)?></strong><p>Coûts unitaires × quantité du CDC</p></div><div><small><?= $d['margin']!==null && $d['margin']<0?'Dépassement':'Solde avant compléments' ?></small><strong class="<?= $d['margin']!==null && $d['margin']<0?'dd-red':'' ?>"><?= $d['margin']===null?'Comparaison impossible':e(ddMoney(abs($d['margin']))) ?></strong><?php if($d['margin']!==null && $d['budgetHT']>0):?><p><?=number_format(100*abs($d['margin'])/$d['budgetHT'],1,',',' ')?> % de l’enveloppe</p><?php endif;?></div></div>
 <?php if($d['margin']!==null && $d['budgetHT']>0):?><div class="dd-track dd-budget-track" aria-label="Base S.T. rapportée au budget"><span style="width:<?=min(100,round(100*$d['lotHT']/$d['budgetHT'],2))?>%" class="<?= $d['margin']<0?'dd-over':'' ?>"></span></div><p class="dd-muted">Couverture S.T. : <?=number_format(100*$d['lotHT']/$d['budgetHT'],1,',',' ')?> % du budget. Le solde ne constitue pas une marge finale.</p><?php else:?><p class="dd-alert">Budget cible ou quantité ou rapprochement fiscal non renseigné — comparaison impossible.</p><?php endif;?>
 <p class="dd-method">Calcul : coûts unitaires de l’Étape 2, chaque S.T. comptée une fois. Logiciel et 3D exclus des achats. <?= $d['vat']===null?'HT et TTC restent séparés, sans conversion supposée.':'Conversion TTC / (1 + '.e((string)$d['vat']).' / 100), taux déclaré dans le CDC.' ?> Aucun coût de tâche n’est ajouté une seconde fois.</p>
 <div class="dd-two"><div><h5>Répartition par type · un équipement</h5><?php $scale=max(array_merge([1],array_map(static fn($g)=>$g['HT']+$g['TTC'], $d['groups']),array_map(static fn($g)=>$g['HT']+$g['TTC'], $d['bySf']))); foreach($d['groups'] as $type=>$g): if(!ddHasCost($type))continue; ?><div class="dd-cost-row"><div><strong><?=e($type)?></strong><span><?=e(ddMoney($g['HT']))?><?= $g['TTC']>0?' + '.e(ddMoney($g['TTC'],'TTC')):'' ?></span></div><div class="dd-track"><span style="width:<?=round(100*$g['HT']/$scale,2)?>%"></span><span class="dd-ttc" style="width:<?=round(100*$g['TTC']/$scale,2)?>%"></span></div></div><?php endforeach;?><p class="dd-muted">Bleu : HT · violet : TTC. Montants séparés ; segments non additionnés fiscalement.</p></div>
 <div><h5>Coûts par sous-fonction · un équipement</h5><?php foreach($d['bySf'] as $sf=>$g):?><div class="dd-cost-row"><div><a href="<?=e($sourceLink(2))?>"><?=e($sf)?></a><span><?=e(ddMoney($g['HT']))?><?= $g['TTC']>0?' + '.e(ddMoney($g['TTC'],'TTC')):'' ?></span></div><div class="dd-track"><span style="width:<?=min(100,round(100*$g['HT']/$scale,2))?>%"></span><span class="dd-ttc" style="width:<?=min(100,round(100*$g['TTC']/$scale,2))?>%"></span></div><small><?=e($d['sfs'][$sf]['description']??'S.F. absente')?></small></div><?php endforeach;?></div></div>
 <?php if($d['current']['count']):?><details class="dd-details"><summary>Rapprochement avec la recherche / les achats actuels (Étapes 4–5)</summary><p><?= $d['current']['ht']===null?e(ddMoney($d['current']['HT']).' + '.ddMoney($d['current']['TTC'],'TTC')):e(ddMoney($d['current']['ht'])) ?> sur <?= $d['current']['count'] ?> lignes renseignées, quantités propres à l’Étape 4. Ce total actualisé est distinct de l’estimation initiale et n’y est pas ajouté.</p><a href="<?=e($sourceLink(4))?>">Consulter références, fournisseurs, quantités et variantes</a></details><?php endif;?>
 </section>
 <section id="dd-time" class="dd-section"><div class="dd-section-head"><h4>Planning & délais</h4><a href="<?=e($cdcLink)?>">Objectifs et planning du CDC</a></div><div class="dd-budget"><div><small>Objectif du CDC</small><strong><?=e(ddDays($d['targetDays']))?></strong><p>Jours calendaires</p></div><div><small>Plus long délai élémentaire</small><strong id="dd-max-delay"><?=e(ddDays($d['maxDelay']))?></strong><p>Base jours des S.T. à confirmer</p></div><div><small>Prototype / marge / retard</small><strong>Non calculables</strong><p>Dépendances et durées incomplètes</p></div></div>
 <?php require __DIR__.'/decision_gantt.php'; ?>
 <h5>Délais connus par S.T.</h5><p class="dd-muted">Les barres sont alignées pour comparer les durées ; elles ne supposent pas un départ simultané.</p>
 <?php foreach($d['lines'] as $line):?><div class="dd-time-row"><a href="<?=e($sourceLink(2))?>"><?=e($line['id'].' · '.$line['type'])?></a><div class="dd-track"><span style="width:<?= $line['delay']!==null && $d['maxDelay']>0?round(100*$line['delay']/$d['maxDelay'],2):0 ?>%" class="<?= $line['delay']===$d['maxDelay']?'dd-long':'' ?>"></span></div><strong><?=e(ddDays($line['delay']))?></strong></div><?php endforeach;?>
 <div class="dd-alert">Pas de somme naïve des délais : ni parallélisation ni chemin critique ne sont suffisamment décrits pour calculer un délai global fiable.</div>
 <details class="dd-details"><summary>Planning textuel et dépendances enregistrées</summary><p class="dd-pre"><?=e($specs['delais']??'Non renseigné')?></p><?php foreach($d['dependencies'] as $t):?><p><a href="<?=url('tache.php?id='.(int)$t['id'])?>">#<?=(int)$t['id']?></a> après #<?=(int)$t['dependance_id']?> · <?=e($t['titre'])?> · échéance <?=e($t['date_echeance']??'non renseignée')?></p><?php endforeach;?><?php if(!$d['dependencies']):?><p>Aucune dépendance de tâche enregistrée.</p><?php endif;?></details>
 </section>
 <section id="dd-risks" class="dd-section"><h4>Points de vigilance avant décision</h4><p class="dd-muted">Les écarts critiques reposent sur les cibles du CDC. Les autres points sont des réserves factuelles à vérifier.</p><div class="dd-risk-grid"><?php foreach($d['risks'] as $r):?><article class="dd-risk"><span class="dd-badge <?= $r['level']==='Critique'?'dd-critical':($r['level']==='Vigilance'?'dd-watch':'dd-unknown') ?>"><?=e($r['impact'].' · '.$r['level'])?></span><h5><?=e($r['subject'])?></h5><p><?=e($r['detail'])?></p><p><strong>Action :</strong> <?=e($r['action'])?></p><a href="<?=e($sourceLink($r['source']))?>">Revoir la source</a></article><?php endforeach;?></div></section>
 <section class="dd-section"><h4>Informations à confirmer <span class="dd-count"><?=count($d['missing'])?></span></h4><div class="dd-missing"><?php foreach($d['missing'] as $m):?><a href="<?=e($m['source']===1?$cdcLink:$sourceLink($m['source']))?>"><strong><?=e($m['subject'])?></strong><small><?=e($m['action'])?></small><span>→</span></a><?php endforeach;?></div></section>
 <section id="dd-summary" class="dd-section dd-summary"><p class="dd-eyebrow">SYNTHÈSE POUR DÉCISION</p><h4><?= $critical?'Écart défavorable identifié':'Projet renseigné, réserves à lever' ?></h4><div class="dd-summary-grid"><div><small>CAPACITÉ</small><strong><?=e($capText)?></strong><p>Disponibilité à confirmer ; <?=count($d['unassigned'])?> tâche(s) sans affectation.</p></div><div><small>COÛT</small><strong><?=e($costText)?></strong><p>Estimation S.T. partielle ; <?= $d['margin']===null?'comparaison impossible':e(ddMoney(abs($d['margin']))).($d['margin']<0?' de dépassement':' avant compléments') ?>.</p></div><div><small>DÉLAI</small><strong>Global à confirmer</strong><p>Objectif <?=e(ddDays($d['targetDays']))?> ; poste le plus long <?=e(ddDays($d['maxDelay']))?>.</p></div></div><p><?=count($d['risks'])?> points de vigilance · <?=count($d['missing'])?> informations à confirmer. La synthèse n’attribue pas automatiquement un GO.</p>
 <?php if($lastDecision):?><p><strong>Dernière décision Étape 3 : <?=e($lastDecision['decision'])?></strong> · <?=e($lastDecision['date_decision'])?> UTC · <?=e($lastDecision['identifiant'])?></p><p class="dd-pre"><?=e($lastDecision['motif'])?></p><?php endif;?>
 <?php if(($projet['go_decision']??'')==='NO_GO'):?><div class="dd-alert">NO GO : projet archivé comme abandonné selon le workflow existant. <a href="<?=e($sourceLink(1))?>">Revoir le besoin</a> · <a href="<?=e($sourceLink(2))?>">Corriger les études</a>. Un nouveau GO réactive le projet.</div><?php endif;?>
 <p>Utilisez la zone Actions et revue pour justifier le GO ou le NO GO. La date, le décideur et le motif sont conservés dans l’historique.</p>
 </section>
 <details class="dd-details"><summary>Contexte, livrables et réserves enregistrés dans le projet</summary><h5>Contraintes du besoin</h5><p class="dd-pre"><?=e($specs['cas_usage']??'Non renseigné')?></p><h5>Livrables</h5><p class="dd-pre"><?=e($specs['livrables_attendus']??'Non renseigné')?></p><h5>Notes / résultats du projet</h5><p class="dd-pre"><?=e($projet['step_notes']??'Non renseigné')?></p><p>Ces textes complètent les calculs structurés ; leurs montants et dates ne sont pas interprétés automatiquement.</p></details>
</div>
